// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_no extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Ugyldig bruk"},
    {"ADF-MF-16004", "Denne funksjonen m\u00E5 IKKE kalles p\u00E5 hovedtr\u00E5den."},
    {"ADF-MF-16022", "Ugyldig argument"},
    {"ADF-MF-16023", "Et nullpakkenavn ble sendt til [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "Egenskapsnavnet kan ikke v\u00E6re null."},
    {"ADF-MF-16027", "Manglende klassenavn."},
    {"ADF-MF-16028", "Manglende metode."},
    {"ADF-MF-16032", "Uventet svar"},
    {"ADF-MF-16033", "CVM-svaret returnerte et nullsvar. "},
    {"ADF-MF-16034", "CVM-svaret returnerte null FeatureContextAccessor."},
    {"ADF-MF-16035", "JS-svaret returnerte null svar."},
    {"ADF-MF-16036", "Kan ikke sende JavaScript-kall til kanalen %@, som ikke har en Web-visning."},
    {"ADF-MF-16074", "Ugyldig melding"},
    {"ADF-MF-16075", "Ukjent meldingstype angitt av meldingen."},
    {"ADF-MF-16092", "Misformet melding"},
    {"ADF-MF-16093", "Tom foresp\u00F8rselsmelding er ikke tillatt."},
    {"ADF-MF-16094", "Melding som ikke st\u00F8ttes"},
    {"ADF-MF-16095", "Systemmeldinger st\u00F8ttes ikke p\u00E5 denne kanalen"},
    {"ADF-MF-16096", "Ugyldig systemforesp\u00F8rsel, %@"},
    {"ADF-MF-16097", "Applikasjonsmeldinger st\u00F8ttes ikke p\u00E5 denne kanalen"},
    {"ADF-MF-16098", "Ugyldig applikasjonsforesp\u00F8rsel, %@"},
    {"ADF-MF-16099", "Ubehandlet melding"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Type: %d Hoveddel: %@"},
    {"ADF-MF-16101", "Mottok en uanmodet svarmelding"},
    {"ADF-MF-16102", "Mottok en ukjent meldingstype"},
    {"ADF-MF-16103", "AdfChannel.handle - feil ved behandling av VMChannel-meldingen: %@ - FEIL: %@"},
    {"ADF-MF-16113", "Finner ikke vedlegget %@, eller det kan ikke leses"},
    {"ADF-MF-16115", "%@ er ikke definert i Web-visningen for funksjonen %@. JavaScript-resultatkallet ble avbrutt."},
    {"ADF-MF-16116", "Det oppstod et problem ved kall til funksjonen %@ i funksjonen %@. Returnert verdi: %@"},
    {"ADF-MF-16133", "Visning av funksjon mislyktes"},
    {"ADF-MF-16134", "Kan ikke vise funksjonen. Fors\u00F8ket p\u00E5 \u00E5 vise funksjonen %@ mislyktes. FEIL: %@"},
    {"ADF-MF-16142", "Kan ikke sende meldingen"},
    {"ADF-MF-16143", "Kan ikke sende meldinger fordi det ikke er noen tilgjengelig tekstmeldingsfunksjon p\u00E5 denne enheten."},
    {"ADF-MF-16144", "Kan ikke sende meldingen fordi tekstmeldingsforfatteren ikke kan hentes."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - klassenavnet ble ikke angitt"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - kallet morphClassName for\u00E5rsaket en FEIL: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - klassenavnet morphClassName mislyktes."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - metoden ble ikke angitt"},
    {"ADF-MF-16149", "Kan ikke opprette klassen %@"},
    {"ADF-MF-16150", "Den forespurte klassen som skal startes, kan ikke opprettes: %@"},
    {"ADF-MF-16151", "En forekomst av klassen %@ svarer ikke til velgeren %@."},
    {"ADF-MF-16152", "Start av %@ for\u00E5rsaket feilen %@"},
    {"ADF-MF-16153", "Serialisering av resultat fra %@ p\u00E5 typen %@ for\u00E5rsaket FEIL: %@"},
    {"ADF-MF-16154", "Serialisering av resultat fra %@ p\u00E5 typen %@ genererte null."},
    {"ADF-MF-16156", "credentialStoreKey for tilkoblingen kan ikke v\u00E6re null"},
    {"ADF-MF-16189", "Logg av"},
    {"ADF-MF-16203", "Finner ikke filen: %@"},
    {"ADF-MF-16204", "E-postmeldingen ble ikke lagret eller lagt i k\u00F8. Dette kan skyldes en feil."},
    {"ADF-MF-16205", "Det oppstod en feil ved fors\u00F8k p\u00E5 \u00E5 lagre e-postmeldingen i utkastmappen."},
    {"ADF-MF-16206", "Det oppstod en feil ved fors\u00F8k p\u00E5 \u00E5 legge e-postmeldingen i k\u00F8 eller sende den."},
    {"ADF-MF-16207", "Det oppstod en ukjent feil ved fors\u00F8k p\u00E5 \u00E5 skrive eller sende en e-post"},
    {"ADF-MF-16208", "Det oppstod en ukjent feil ved fors\u00F8k p\u00E5 \u00E5 skrive eller sende en tekstmelding"},
    {"ADF-MF-16209", "Finner ikke filen"},
    {"ADF-MF-16213", "Kall til start av Java p\u00E5 en annen funksjon er ikke tillatt."},
    {"ADF-MF-16214", "Brudd p\u00E5 tilgangstillatelse"},
    {"ADF-MF-16215", "Kan ikke kryptere passord: %@"},
    {"ADF-MF-16216", "Kan ikke generere passord via n\u00F8kkelindeksering: %@"},
    {"ADF-MF-16217", "Kan ikke dekryptere passord: %@"},
    {"ADF-MF-16218", "Ugyldig parametern\u00F8kkel. ParameterKey = %@"},
    {"ADF-MF-16219", "loginComplete mislyktes med unntaket %@"},
    {"ADF-MF-16220", "Kan ikke fastsette returtypen for klassen %@ for metoden %@."},
    {"ADF-MF-16221", "Ugyldig returtype for metoden %@ i klassen %@."},
    {"ADF-MF-16222", "Det oppstod et problem ved levering av dataendringshendelsene til funksjonen %1@ med JSON-nyttelasten %2@. Forventet returverdi var %3@, men faktisk returverdi var %4@."},
    {"ADF-MF-16223", "Det er ikke angitt noe varsel-ID i argumenter"},
    {"ADF-MF-16224", "Kan ikke planlegge et lokalt varsel, ugyldig dato er angitt"},
    {"ADF-MF-16225", "Kan ikke planlegge et lokalt varsel, ugyldig gjentagelsesintervall er angitt"},
    {"ADF-MF-16226", "Kan ikke planlegge et lokalt varsel, ugyldig merke er angitt"},
    {"ADF-MF-16227", "Kan ikke planlegge et lokalt varsel, ugyldig lyd er angitt"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
