// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_pt extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Utiliza\u00E7\u00E3o Inv\u00E1lida"},
    {"ADF-MF-16004", "\u00C9 necess\u00E1rio que esta fun\u00E7\u00E3o N\u00C3O seja chamada no processo leve principal."},
    {"ADF-MF-16022", "Argumento Inv\u00E1lido"},
    {"ADF-MF-16023", "Foi transmitido um nome de pacote nulo a [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "N\u00E3o \u00E9 poss\u00EDvel que o nome da propriedade seja nulo."},
    {"ADF-MF-16027", "Falta o nome da classe."},
    {"ADF-MF-16028", "Falta o m\u00E9todo."},
    {"ADF-MF-16032", "Resposta Inesperada"},
    {"ADF-MF-16033", "A Resposta do CVM devolveu uma resposta nula. "},
    {"ADF-MF-16034", "A Resposta do CVM devolveu um FeatureContextAccessor nulo."},
    {"ADF-MF-16035", "A Resposta do JS devolveu uma resposta nula."},
    {"ADF-MF-16036", "N\u00E3o \u00E9 poss\u00EDvel enviar chamadas de JavaScript para o canal '%@' que n\u00E3o tem uma visualiza\u00E7\u00E3o na Web."},
    {"ADF-MF-16074", "Mensagem Inv\u00E1lida"},
    {"ADF-MF-16075", "Tipo de Mensagem Desconhecido especificado pela mensagem."},
    {"ADF-MF-16092", "Mensagem Incorreta"},
    {"ADF-MF-16093", "N\u00E3o \u00E9 permitida uma mensagem de pedido vazia."},
    {"ADF-MF-16094", "Mensagem N\u00E3o Suportada"},
    {"ADF-MF-16095", "N\u00E3o s\u00E3o suportadas mensagens do sistema neste canal"},
    {"ADF-MF-16096", "O pedido do sistema %@ \u00E9 inv\u00E1lido"},
    {"ADF-MF-16097", "N\u00E3o s\u00E3o suportadas mensagens da aplica\u00E7\u00E3o neste canal"},
    {"ADF-MF-16098", "O pedido da aplica\u00E7\u00E3o %@ \u00E9 inv\u00E1lido"},
    {"ADF-MF-16099", "Mensagem N\u00E3o Tratada"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Tipo: %d Corpo: %@"},
    {"ADF-MF-16101", "Foi recebida uma mensagem de resposta n\u00E3o solicitada"},
    {"ADF-MF-16102", "Foi recebido um tipo de mensagem desconhecido"},
    {"ADF-MF-16103", "AdfChannel.handle - Erro no tratamento da mensagem do VMChannel: %@ - ERRO: %@"},
    {"ADF-MF-16113", "O anexo %@ n\u00E3o foi encontrado ou n\u00E3o foi poss\u00EDvel l\u00EA-lo"},
    {"ADF-MF-16115", "%@ n\u00E3o est\u00E1 definido na visualiza\u00E7\u00E3o na Web para a funcionalidade %@. A chamada de resultado de JavaScript foi abortada."},
    {"ADF-MF-16116", "Ocorr\u00EAncia de problema na chamada da fun\u00E7\u00E3o '%@' na funcionalidade %@. Valor devolvido: %@"},
    {"ADF-MF-16133", "Falha na Apresenta\u00E7\u00E3o da Funcionalidade"},
    {"ADF-MF-16134", "N\u00E3o foi poss\u00EDvel mostrar a funcionalidade. Falha na tentativa de apresenta\u00E7\u00E3o da funcionalidade '%@'. ERRO: %@"},
    {"ADF-MF-16142", "N\u00E3o \u00C9 Poss\u00EDvel Enviar a Mensagem"},
    {"ADF-MF-16143", "Incapaz de enviar a mensagem, porque o servi\u00E7o de mensagens de texto n\u00E3o est\u00E1 dispon\u00EDvel neste dispositivo."},
    {"ADF-MF-16144", "Incapaz de enviar a mensagem, porque n\u00E3o foi poss\u00EDvel obter o editor de mensagens de texto."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - O 'classname' n\u00E3o foi especificado"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - A chamada de morphClassName causou um ERRO: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Falha no morphClassName do 'classname'."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - O 'method' n\u00E3o foi especificado"},
    {"ADF-MF-16149", "N\u00E3o foi poss\u00EDvel criar a classe: %@"},
    {"ADF-MF-16150", "N\u00E3o foi poss\u00EDvel criar a classe pedida para ser invocada: %@"},
    {"ADF-MF-16151", "A inst\u00E2ncia da classe %@ n\u00E3o responde ao seletor '%@'."},
    {"ADF-MF-16152", "A invoca\u00E7\u00E3o de '%@' causou o erro: %@"},
    {"ADF-MF-16153", "A sequencia\u00E7\u00E3o do resultado de '%@' no tipo %@ causou o ERRO: %@"},
    {"ADF-MF-16154", "A sequencia\u00E7\u00E3o do resultado de '%@' no tipo %@ gerou um valor nulo."},
    {"ADF-MF-16156", "N\u00E3o \u00E9 poss\u00EDvel que a credentialStoreKey da liga\u00E7\u00E3o seja nula"},
    {"ADF-MF-16189", "Sair de Sess\u00E3o"},
    {"ADF-MF-16203", "O ficheiro n\u00E3o foi encontrado: %@"},
    {"ADF-MF-16204", "A mensagem de correio eletr\u00F3nico n\u00E3o foi gravada nem colocada na fila de espera, possivelmente devido a um erro."},
    {"ADF-MF-16205", "Ocorr\u00EAncia de erro na tentativa de grava\u00E7\u00E3o da mensagem de correio eletr\u00F3nico na pasta Rascunhos."},
    {"ADF-MF-16206", "Ocorr\u00EAncia de erro na tentativa de coloca\u00E7\u00E3o na fila de espera ou envio da mensagem de correio eletr\u00F3nico."},
    {"ADF-MF-16207", "Ocorr\u00EAncia de erro desconhecido na tentativa de composi\u00E7\u00E3o ou envio da mensagem de correio eletr\u00F3nico"},
    {"ADF-MF-16208", "Ocorr\u00EAncia de erro desconhecido na tentativa de composi\u00E7\u00E3o ou envio da mensagem de texto"},
    {"ADF-MF-16209", "O ficheiro n\u00E3o foi encontrado"},
    {"ADF-MF-16213", "N\u00E3o \u00E9 permitido chamar a Invoca\u00E7\u00E3o de Java noutra funcionalidade."},
    {"ADF-MF-16214", "Viola\u00E7\u00E3o de acesso"},
    {"ADF-MF-16215", "Incapaz de codificar a senha: %@"},
    {"ADF-MF-16216", "Incapaz de gerar senha atrav\u00E9s de hashing: %@"},
    {"ADF-MF-16217", "Incapaz de descodificar a senha: %@"},
    {"ADF-MF-16218", "Chave de par\u00E2metro inv\u00E1lida. ParameterKey= %@"},
    {"ADF-MF-16219", "Falha de loginComplete com a exce\u00E7\u00E3o: %@"},
    {"ADF-MF-16220", "N\u00E3o foi poss\u00EDvel determinar o tipo de retorno da classe %@ do m\u00E9todo %@."},
    {"ADF-MF-16221", "Tipo de retorno inv\u00E1lido para o m\u00E9todo %@ na classe %@."},
    {"ADF-MF-16222", "Ocorreu um problema ao fornecer os eventos de altera\u00E7\u00E3o de dados \u00E0 funcionalidade '%1@' com payload de JSON '%2@'. O valor devolvido esperado era '%3@' mas foi '%4@'."},
    {"ADF-MF-16223", "Nenhuma ID de notifica\u00E7\u00E3o especificada nos argumentos"},
    {"ADF-MF-16224", "Incapaz de agendar uma notifica\u00E7\u00E3o local, data inv\u00E1lida especificada"},
    {"ADF-MF-16225", "Incapaz de agendar uma notifica\u00E7\u00E3o local, intervalo de repeti\u00E7\u00E3o inv\u00E1lido especificado"},
    {"ADF-MF-16226", "Incapaz de agendar uma notifica\u00E7\u00E3o local, data inv\u00E1lida especificada"},
    {"ADF-MF-16227", "Incapaz de agendar uma notifica\u00E7\u00E3o local, som inv\u00E1lido especificado"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
