// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_sk extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Neplatn\u00E9 pou\u017Eitie"},
    {"ADF-MF-16004", "T\u00E1to funkcia sa nesmie vola\u0165 na hlavnom vl\u00E1kne."},
    {"ADF-MF-16022", "Neplatn\u00FD argument"},
    {"ADF-MF-16023", "Do met\u00F3dy [oraADFLogger getLogger:] bol odovzdan\u00FD nulov\u00FD n\u00E1zov bal\u00EDka."},
    {"ADF-MF-16025", "N\u00E1zov vlastnosti nem\u00F4\u017Ee by\u0165 nulov\u00FD."},
    {"ADF-MF-16027", "Ch\u00FDba n\u00E1zov triedy."},
    {"ADF-MF-16028", "Ch\u00FDba met\u00F3da."},
    {"ADF-MF-16032", "Neo\u010Dak\u00E1van\u00E1 odozva"},
    {"ADF-MF-16033", "Odozva CVM vr\u00E1tila nulov\u00FA odozvu. "},
    {"ADF-MF-16034", "Odozva CVM vr\u00E1tila nulov\u00FA polo\u017Eku FeatureContextAccessor."},
    {"ADF-MF-16035", "Odozva JS vr\u00E1tila nulov\u00FA odozvu."},
    {"ADF-MF-16036", "Nemo\u017Eno odosla\u0165 volania skriptu JavaScript do kan\u00E1la '%@', ktor\u00FD nem\u00E1 webov\u00E9 zobrazenie."},
    {"ADF-MF-16074", "Neplatn\u00E1 spr\u00E1va"},
    {"ADF-MF-16075", "V spr\u00E1ve je zadan\u00FD nezn\u00E1my typ spr\u00E1vy."},
    {"ADF-MF-16092", "Chybne vytvoren\u00E9 hl\u00E1senie"},
    {"ADF-MF-16093", "Pr\u00E1zdne hl\u00E1senie po\u017Eiadavky nie je povolen\u00E9."},
    {"ADF-MF-16094", "Nepodporovan\u00E9 hl\u00E1senie"},
    {"ADF-MF-16095", "Syst\u00E9mov\u00E9 hl\u00E1senia nie s\u00FA na tomto kan\u00E1li podporovan\u00E9"},
    {"ADF-MF-16096", "Neplatn\u00E1 syst\u00E9mov\u00E1 po\u017Eiadavka %@"},
    {"ADF-MF-16097", "Hl\u00E1senia aplik\u00E1cie nie s\u00FA na tomto kan\u00E1li podporovan\u00E9"},
    {"ADF-MF-16098", "Neplatn\u00E1 po\u017Eiadavka aplik\u00E1cie %@"},
    {"ADF-MF-16099", "Nespracovan\u00E9 hl\u00E1senie"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Typ: %d Telo: %@"},
    {"ADF-MF-16101", "Bolo prijat\u00E9 hl\u00E1senie nevy\u017Eiadanej odozvy"},
    {"ADF-MF-16102", "Bol prijat\u00FD nezn\u00E1my typ hl\u00E1senia"},
    {"ADF-MF-16103", "AdfChannel.handle - Chyba pri spracovan\u00ED hl\u00E1senia VMChannel: %@ - CHYBA: %@"},
    {"ADF-MF-16113", "Pr\u00EDloha %@ sa nena\u0161la alebo sa ju nepodarilo pre\u010D\u00EDta\u0165"},
    {"ADF-MF-16115", "Polo\u017Eka %@ nie je definovan\u00E1 vo webview pre funkciu %@. Volanie v\u00FDsledku skriptu JavaScript bolo preru\u0161en\u00E9."},
    {"ADF-MF-16116", "Pri volan\u00ED funkcie %@ sa vyskytol probl\u00E9m vo funkcii %@. Vr\u00E1tila sa hodnota: %@"},
    {"ADF-MF-16133", "Zobrazenie funkcie zlyhalo"},
    {"ADF-MF-16134", "Nepodarilo sa zobrazi\u0165 funkciu. Pokus o zobrazenie funkcie \"%@\" zlyhal. CHYBA: %@"},
    {"ADF-MF-16142", "Spr\u00E1vu nie je mo\u017En\u00E9 odosla\u0165"},
    {"ADF-MF-16143", "Spr\u00E1vu nie je mo\u017En\u00E9 odosla\u0165, preto\u017Ee v tomto zariaden\u00ED nie je k dispoz\u00EDcii posielanie spr\u00E1v SMS."},
    {"ADF-MF-16144", "Spr\u00E1vu nie je mo\u017En\u00E9 odosla\u0165, preto\u017Ee sa nepodarilo na\u010D\u00EDta\u0165 program na vytvorenie textovej spr\u00E1vy."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - parameter 'classname' nebol zadan\u00FD"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - volanie morphClassName sp\u00F4sobilo chybu: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - zlyhanie 'classname' morphClassName."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - parameter 'method' nebol zadan\u00FD"},
    {"ADF-MF-16149", "Nepodarilo sa vytvori\u0165 triedu: %@"},
    {"ADF-MF-16150", "Po\u017Eadovan\u00FA triedu, ktor\u00E1 sa m\u00E1 vyvola\u0165, nebolo mo\u017En\u00E9 vytvori\u0165: %@"},
    {"ADF-MF-16151", "In\u0161tancia triedy %@ neodpoved\u00E1 selektoru '%@'."},
    {"ADF-MF-16152", "Vyvolanie '%@' sp\u00F4sobilo chybu: %@"},
    {"ADF-MF-16153", "Serializ\u00E1cia v\u00FDsledku z'%@' pre typ %@ sp\u00F4sobila chybu: %@"},
    {"ADF-MF-16154", "Serializ\u00E1cia v\u00FDsledku z'%@' pre typ %@ vygenerovala nulov\u00FA hodnotu."},
    {"ADF-MF-16156", "K\u013E\u00FA\u010D credentialStoreKey pre pripojenie nem\u00F4\u017Ee ma\u0165 nulov\u00FA hodnotu"},
    {"ADF-MF-16189", "Odhl\u00E1senie"},
    {"ADF-MF-16203", "S\u00FAbor sa nena\u0161iel: %@"},
    {"ADF-MF-16204", "E-mailov\u00E1 spr\u00E1va nebola ulo\u017Een\u00E1 ani zaraden\u00E1 do frontu, pravdepodobne v d\u00F4sledku chyby."},
    {"ADF-MF-16205", "Pri pokuse o ulo\u017Eenie e-mailovej spr\u00E1vy do prie\u010Dinka Koncepty sa vyskytla chyba."},
    {"ADF-MF-16206", "Pri pokuse o zaradenie e-mailovej spr\u00E1vy do frontu alebo o jej odoslanie sa vyskytla chyba."},
    {"ADF-MF-16207", "Pri pokuse o vytvorenie alebo odoslanie e-mailovej spr\u00E1vy sa vyskytla nezn\u00E1ma chyba"},
    {"ADF-MF-16208", "Pri pokuse o vytvorenie alebo odoslanie textovej spr\u00E1vy sa vyskytla nezn\u00E1ma chyba"},
    {"ADF-MF-16209", "S\u00FAbor sa nena\u0161iel"},
    {"ADF-MF-16213", "Volanie \"Vyvola\u0165 met\u00F3du Java\" pre in\u00FA funkciu nie je povolen\u00E9."},
    {"ADF-MF-16214", "Poru\u0161enie pr\u00EDstupu"},
    {"ADF-MF-16215", "Nemo\u017Eno za\u0161ifrova\u0165 heslo: %@"},
    {"ADF-MF-16216", "Nemo\u017Eno generova\u0165 heslo prostredn\u00EDctvom ha\u0161ovania: %@"},
    {"ADF-MF-16217", "Nemo\u017Eno de\u0161ifrova\u0165 heslo: %@"},
    {"ADF-MF-16218", "Neplatn\u00FD k\u013E\u00FA\u010D parametra. ParameterKey= %@"},
    {"ADF-MF-16219", "Met\u00F3da loginComplete zlyhala s v\u00FDnimkou: %@"},
    {"ADF-MF-16220", "Nepodarilo sa ur\u010Di\u0165 n\u00E1vratov\u00FD typ triedy %@ pre met\u00F3du %@."},
    {"ADF-MF-16221", "Neplatn\u00FD n\u00E1vratov\u00FD typ pre met\u00F3du %@ v triede %@."},
    {"ADF-MF-16222", "Nastal probl\u00E9m pri doru\u010Dovan\u00ED udalost\u00ED zmien d\u00E1t do funkcie %1@ s d\u00E1tami JSON payload %2@. O\u010Dak\u00E1van\u00E1 n\u00E1vratov\u00E1 hodnota je %3@, ale vr\u00E1tila sa hodnota %4@."},
    {"ADF-MF-16223", "V argumentoch nie je zadan\u00E9 \u017Eiadne ID upozornenia"},
    {"ADF-MF-16224", "Nie je mo\u017En\u00E9 napl\u00E1nova\u0165 lok\u00E1lne upozornenie, zadan\u00FD je neplatn\u00FD d\u00E1tum"},
    {"ADF-MF-16225", "Nie je mo\u017En\u00E9 napl\u00E1nova\u0165 lok\u00E1lne upozornenie, zadan\u00FD je neplatn\u00FD interval opakovania"},
    {"ADF-MF-16226", "Nie je mo\u017En\u00E9 napl\u00E1nova\u0165 lok\u00E1lne upozornenie, zadan\u00FD je neplatn\u00FD \u0161t\u00EDtok"},
    {"ADF-MF-16227", "Nie je mo\u017En\u00E9 napl\u00E1nova\u0165 lok\u00E1lne upozornenie, zadan\u00FD je neplatn\u00FD zvuk"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
