// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_hu extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "\u00C9rv\u00E9nytelen haszn\u00E1lat"},
    {"ADF-MF-16004", "Ezt a f\u00FCggv\u00E9nyt NEM szabad a f\u0151sz\u00E1lon h\u00EDvni."},
    {"ADF-MF-16022", "\u00C9rv\u00E9nytelen argumentum"},
    {"ADF-MF-16023", "\u00DCres csomagn\u00E9v lett \u00E1tadva [oraADFLogger getLogger:] sz\u00E1m\u00E1ra."},
    {"ADF-MF-16025", "Tulajdons\u00E1gn\u00E9v nem lehet \u00FCres."},
    {"ADF-MF-16027", "Hi\u00E1nyz\u00F3 oszt\u00E1lyn\u00E9v."},
    {"ADF-MF-16028", "Hi\u00E1nyz\u00F3 met\u00F3dus."},
    {"ADF-MF-16032", "V\u00E1ratlan v\u00E1lasz"},
    {"ADF-MF-16033", "A CVM Response \u00FCres v\u00E1laszt adott vissza. "},
    {"ADF-MF-16034", "A CVM Response \u00FCres FeatureContextAccessor \u00E9rt\u00E9ket adott vissza."},
    {"ADF-MF-16035", "A JS Response \u00FCres v\u00E1laszt adott vissza."},
    {"ADF-MF-16036", "Nem k\u00FCldhet\u0151k JavaScript h\u00EDv\u00E1sok az olyan '%@' csatorn\u00E1ra, amelyiknek nincs webes megjelen\u00EDt\u00E9se."},
    {"ADF-MF-16074", "\u00C9rv\u00E9nytelen \u00FCzenet"},
    {"ADF-MF-16075", "Az \u00FCzenet ismeretlen \u00FCzenett\u00EDpust adott meg."},
    {"ADF-MF-16092", "Helytelen form\u00E1tum\u00FA \u00FCzenet"},
    {"ADF-MF-16093", "\u00DCres k\u00E9relem\u00FCzenet nem megengedett."},
    {"ADF-MF-16094", "Nem t\u00E1mogatott \u00FCzenet"},
    {"ADF-MF-16095", "Rendszer\u00FCzenetek nem haszn\u00E1lhat\u00F3k ezen a csatorn\u00E1n"},
    {"ADF-MF-16096", "\u00C9rv\u00E9nytelen rendszerk\u00E9relem: %@"},
    {"ADF-MF-16097", "Alkalmaz\u00E1s\u00FCzenetek nem haszn\u00E1lhat\u00F3k ezen a csatorn\u00E1n"},
    {"ADF-MF-16098", "\u00C9rv\u00E9nytelen alkalmaz\u00E1sk\u00E9relem: %@"},
    {"ADF-MF-16099", "Nem kezelt \u00FCzenet"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Type: %d Body: %@"},
    {"ADF-MF-16101", "K\u00E9retlen v\u00E1lasz\u00FCzenet \u00E9rkezett"},
    {"ADF-MF-16102", "Ismeretlen \u00FCzenett\u00EDpus \u00E9rkezett"},
    {"ADF-MF-16103", "AdfChannel.handle - Hiba a VMChannel \u00FCzenet kezel\u00E9sekor: %@ - HIBA: %@"},
    {"ADF-MF-16113", "A(z) %@ mell\u00E9klet nem tal\u00E1lhat\u00F3 vagy nem olvashat\u00F3"},
    {"ADF-MF-16115", "%@ nincs defini\u00E1lva a WebView rendszerben a(z) %@ szolg\u00E1ltat\u00E1shoz. JavaScript eredm\u00E9nyh\u00EDv\u00E1s megszak\u00EDtva."},
    {"ADF-MF-16116", "Nem siker\u00FClt a(z) '%@' f\u00FCggv\u00E9ny h\u00EDv\u00E1sa a(z) %@ szolg\u00E1ltat\u00E1sban. Visszaadott \u00E9rt\u00E9k: %@"},
    {"ADF-MF-16133", "Szolg\u00E1ltat\u00E1s megjelen\u00EDt\u00E9se sikertelen"},
    {"ADF-MF-16134", "Szolg\u00E1ltat\u00E1s nem jelen\u00EDthet\u0151 meg. A(z) \"%@\" szolg\u00E1ltat\u00E1s megjelen\u00EDt\u00E9si k\u00EDs\u00E9rlete sikertelen. HIBA: %@"},
    {"ADF-MF-16142", "Nem k\u00FCldhet\u0151 \u00FCzenet"},
    {"ADF-MF-16143", "Nem lehet \u00FCzenetet k\u00FCldeni, mivel az \u00FCzenetk\u00FCld\u00E9s nem el\u00E9rhet\u0151 ezen a k\u00E9sz\u00FCl\u00E9ken."},
    {"ADF-MF-16144", "Nem lehet \u00FCzenetet k\u00FCldeni, mert nem olvashat\u00F3 be a sz\u00F6veges \u00FCzenet szerkeszt\u0151je."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - Nem lett megadva az 'oszt\u00E1lyn\u00E9v'"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - A morphClassName h\u00EDv\u00E1s HIB\u00C1T okozott: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Sikertelen a morphClassName 'oszt\u00E1lyneve'."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - Nem lett megadva a 'met\u00F3dus'"},
    {"ADF-MF-16149", "Nem hozhat\u00F3 l\u00E9tre oszt\u00E1ly: %@"},
    {"ADF-MF-16150", "A h\u00EDvni k\u00EDv\u00E1nt k\u00E9rt oszt\u00E1ly nem hozhat\u00F3 l\u00E9tre: %@"},
    {"ADF-MF-16151", "A(z) %@ oszt\u00E1ly p\u00E9ld\u00E1nya nem v\u00E1laszol a(z) '%@' v\u00E1laszt\u00F3nak."},
    {"ADF-MF-16152", "'%@' h\u00EDv\u00E1sa hib\u00E1t okozott: %@"},
    {"ADF-MF-16153", "A(z) '%@' eredm\u00E9nyeinek a(z) %@ t\u00EDpus szerint szerializ\u00E1l\u00E1sa HIB\u00C1T okozott: %@"},
    {"ADF-MF-16154", "A(z) '%@' eredm\u00E9nyeinek a(z) %@ t\u00EDpus szerint szerializ\u00E1l\u00E1sa semmire mutat\u00F3 pointert \u00E1ll\u00EDtott el\u0151."},
    {"ADF-MF-16156", "A kapcsolat credentialStoreKey \u00E9rt\u00E9ke nem lehet \u00FCres"},
    {"ADF-MF-16189", "Kijelentkez\u00E9s"},
    {"ADF-MF-16203", "A f\u00E1jl nem tal\u00E1lhat\u00F3: %@"},
    {"ADF-MF-16204", "Val\u00F3sz\u00EDn\u0171leg egy hiba miatt az e-mail \u00FCzenetet nem lehetett elmenteni vagy sorba \u00E1ll\u00EDtani."},
    {"ADF-MF-16205", "Hiba t\u00F6rt\u00E9nt az e-mail \u00FCzenet Piszkozatok mapp\u00E1ba val\u00F3 ment\u00E9sekor."},
    {"ADF-MF-16206", "Hiba t\u00F6rt\u00E9nt az e-mail \u00FCzenet sorba \u00E1ll\u00EDt\u00E1sa vagy k\u00FCld\u00E9se k\u00F6zben."},
    {"ADF-MF-16207", "Ismeretlen hiba t\u00F6rt\u00E9nt az e-mail \u00FCzenet \u00EDr\u00E1sa vagy k\u00FCld\u00E9se k\u00F6zben"},
    {"ADF-MF-16208", "Ismeretlen hiba t\u00F6rt\u00E9nt a sz\u00F6veges \u00FCzenet \u00EDr\u00E1sa vagy k\u00FCld\u00E9se k\u00F6zben"},
    {"ADF-MF-16209", "A f\u00E1jl nem tal\u00E1lhat\u00F3"},
    {"ADF-MF-16213", "Java h\u00EDv\u00E1sa m\u00E1sik szolg\u00E1ltat\u00E1son nem megengedett."},
    {"ADF-MF-16214", "Hozz\u00E1f\u00E9r\u00E9s megs\u00E9rt\u00E9se"},
    {"ADF-MF-16215", "Nem lehet k\u00F3dolni a jelsz\u00F3t: %@"},
    {"ADF-MF-16216", "Nem lehet jelsz\u00F3t el\u0151\u00E1ll\u00EDtani kivonatol\u00E1ssal: %@"},
    {"ADF-MF-16217", "Nem lehet dek\u00F3dolni a jelsz\u00F3t: %@"},
    {"ADF-MF-16218", "\u00C9rv\u00E9nytelen a param\u00E9terkulcs. A ParameterKey= %@"},
    {"ADF-MF-16219", "loginComplete sikertelen, kiv\u00E9tel t\u00F6rt\u00E9nt: %@"},
    {"ADF-MF-16220", "Nem hat\u00E1rozhat\u00F3 meg a(z) %@ oszt\u00E1ly visszat\u00E9r\u00E9si \u00E9rt\u00E9k\u00E9nek a t\u00EDpusa a(z) %@ met\u00F3dusn\u00E1l"},
    {"ADF-MF-16221", "\u00C9rv\u00E9ntelen a(z) %@ met\u00F3dus visszat\u00E9r\u00E9si \u00E9rt\u00E9k\u00E9nek a t\u00EDpusa a(z) %@ oszt\u00E1lyban"},
    {"ADF-MF-16222", "Nem siker\u00FClt az adatm\u00F3dos\u00EDt\u00E1si esem\u00E9nyek tov\u00E1bb\u00EDt\u00E1sa a(z) '%1@' szolg\u00E1ltat\u00E1sba, JSON adatt\u00F6rzs: '%2@'. V\u00E1rt visszat\u00E9r\u00E9si \u00E9rt\u00E9k: '%3@', t\u00E9nylegesen kapott: '%4@'."},
    {"ADF-MF-16223", "Nincs \u00E9rtes\u00EDt\u00E9sazonos\u00EDt\u00F3 megadva az argumentumokban"},
    {"ADF-MF-16224", "Nem \u00FCtemezhet\u0151 a helyi \u00E9rtes\u00EDt\u00E9s, \u00E9rv\u00E9nytelen d\u00E1tum lett megadva"},
    {"ADF-MF-16225", "Nem \u00FCtemezhet\u0151 a helyi \u00E9rtes\u00EDt\u00E9s, \u00E9rv\u00E9nytelen ism\u00E9tl\u00E9si gyakoris\u00E1g lett megadva"},
    {"ADF-MF-16226", "Nem \u00FCtemezhet\u0151 a helyi \u00E9rtes\u00EDt\u00E9s, \u00E9rv\u00E9nytelen jelv\u00E9ny lett megadva"},
    {"ADF-MF-16227", "Nem \u00FCtemezhet\u0151 a helyi \u00E9rtes\u00EDt\u00E9s, \u00E9rv\u00E9nytelen hang lett megadva"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
