// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_pt_BR extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Uso Inv\u00E1lido"},
    {"ADF-MF-16004", "Esta fun\u00E7\u00E3o N\u00C3O deve ser chamada no thread principal."},
    {"ADF-MF-16022", "Argumento Inv\u00E1lido"},
    {"ADF-MF-16023", "Um nome de pacote nulo foi informado para [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "O nome da propriedade n\u00E3o pode ser nulo."},
    {"ADF-MF-16027", "Classname n\u00E3o encontrado."},
    {"ADF-MF-16028", "M\u00E9todo n\u00E3o encontrado."},
    {"ADF-MF-16032", "Resposta Inesperada"},
    {"ADF-MF-16033", "A Resposta CVM retornou uma resposta nula. "},
    {"ADF-MF-16034", "A Resposta CVM retornou um FeatureContextAccessor nulo."},
    {"ADF-MF-16035", "A Resposta JS retornou uma resposta nula."},
    {"ADF-MF-16036", "N\u00E3o \u00E9 poss\u00EDvel enviar chamadas JavaScript para canal '%@', que n\u00E3o tem uma webview."},
    {"ADF-MF-16074", "Mensagem inv\u00E1lida"},
    {"ADF-MF-16075", "Tipo de Mensagem Desconhecido especificado pela mensagem."},
    {"ADF-MF-16092", "Mensagem Incorreta"},
    {"ADF-MF-16093", "Mensagem de solicita\u00E7\u00E3o vazia n\u00E3o permitida."},
    {"ADF-MF-16094", "Mensagem N\u00E3o Suportada"},
    {"ADF-MF-16095", "As mensagens do sistema n\u00E3o s\u00E3o suportadas neste canal"},
    {"ADF-MF-16096", "Solicita\u00E7\u00E3o %@ do sistema inv\u00E1lida"},
    {"ADF-MF-16097", "As mensagens da aplica\u00E7\u00E3o n\u00E3o s\u00E3o suportadas neste canal"},
    {"ADF-MF-16098", "Solicita\u00E7\u00E3o %@ da aplica\u00E7\u00E3o inv\u00E1lida"},
    {"ADF-MF-16099", "Mensagem N\u00E3o Tratada"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Tipo: %d Corpo: %@"},
    {"ADF-MF-16101", "Recebeu uma mensagem de resposta n\u00E3o solicitada"},
    {"ADF-MF-16102", "Recebeu um tipo de mensagem desconhecido"},
    {"ADF-MF-16103", "AdfChannel.handle - Erro ao tratar a mensagem VMChannel: %@ - ERRO: %@"},
    {"ADF-MF-16113", "O anexo %@ n\u00E3o foi encontrado ou n\u00E3o p\u00F4de ser lido"},
    {"ADF-MF-16115", "%@ n\u00E3o definido na webview para a funcionalidade %@. Chamada resultante de JavaScript abortada."},
    {"ADF-MF-16116", "Houve um problema ao chamar a fun\u00E7\u00E3o '%@' na funcionalidade %@. Valor retornado: %@"},
    {"ADF-MF-16133", "Falha ao Mostrar o Recurso"},
    {"ADF-MF-16134", "N\u00E3o foi poss\u00EDvel mostrar o recurso. Falha na tentativa de mostrar o recurso '%@'. ERRO: %@"},
    {"ADF-MF-16142", "N\u00E3o \u00E9 Poss\u00EDvel Enviar Mensagem"},
    {"ADF-MF-16143", "N\u00E3o \u00E9 poss\u00EDvel enviar mensagem porque mensagem de texto n\u00E3o est\u00E1 dispon\u00EDvel neste dispositivo."},
    {"ADF-MF-16144", "N\u00E3o \u00E9 poss\u00EDvel enviar mensagem ou obter o construtor da mensagem."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - O \"nome da classe\" n\u00E3o foi especificado"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - A chamada morphClassName provocou um ERRO: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Falha no morphClassName do \"nome da classe\"."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - O \"m\u00E9todo\" n\u00E3o foi especificado"},
    {"ADF-MF-16149", "N\u00E3o foi poss\u00EDvel criar a classe: %@"},
    {"ADF-MF-16150", "A classe solicitada a ser chamada n\u00E3o p\u00F4de ser criada: %@"},
    {"ADF-MF-16151", "Inst\u00E2ncia da classe %@ n\u00E3o responde ao seletor \"%@\"."},
    {"ADF-MF-16152", "Chamar \"%@\" provocou um erro: %@"},
    {"ADF-MF-16153", "A serializa\u00E7\u00E3o dos resultados de \"%@\" no tipo %@ causou o ERRO: %@"},
    {"ADF-MF-16154", "A serializa\u00E7\u00E3o dos resultados de \"%@\" no tipo %@ gerou nulo."},
    {"ADF-MF-16156", "A credentialStoreKey para a conex\u00E3o n\u00E3o pode ser nula"},
    {"ADF-MF-16189", "Efetuar Log-out"},
    {"ADF-MF-16203", "Arquivo n\u00E3o encontrado: %@"},
    {"ADF-MF-16204", "A mensagem de e-mail n\u00E3o foi salva nem colocada na fila, provavelmente devido a um erro."},
    {"ADF-MF-16205", "Ocorreu um erro ao tentar salvar a mensagem de email na pasta Rascunhos."},
    {"ADF-MF-16206", "Ocorreu um erro ao tentar enviar ou colocar a mensagem de e-mail na fila."},
    {"ADF-MF-16207", "Ocorreu um erro desconhecido ao tentar compor ou enviar um e-mail"},
    {"ADF-MF-16208", "Ocorreu um erro desconhecido ao tentar compor ou enviar uma mensagem de texto"},
    {"ADF-MF-16209", "Arquivo n\u00E3o encontrado"},
    {"ADF-MF-16213", "N\u00E3o \u00E9 permitido chamar Java em outra funcionalidade."},
    {"ADF-MF-16214", "Viola\u00E7\u00E3o de acesso"},
    {"ADF-MF-16215", "N\u00E3o \u00E9 poss\u00EDvel criptografar a senha: %@"},
    {"ADF-MF-16216", "N\u00E3o \u00E9 poss\u00EDvel gerar a senha via hash: %@"},
    {"ADF-MF-16217", "N\u00E3o \u00E9 poss\u00EDvel decriptografar a senha: %@"},
    {"ADF-MF-16218", "Chave de par\u00E2metro inv\u00E1lido. ParameterKey= %@"},
    {"ADF-MF-16219", "Falha em loginComplete com a exce\u00E7\u00E3o: %@"},
    {"ADF-MF-16220", "N\u00E3o foi poss\u00EDvel determinar o tipo de retorno da classe %@ do m\u00E9todo %@."},
    {"ADF-MF-16221", "Tipo de retorno inv\u00E1lido para o m\u00E9todo %@ na classe %@."},
    {"ADF-MF-16222", "Houve um problema ao entregar os eventos de altera\u00E7\u00E3o de dados \u00E0 funcionalidade '%1@' com a carga de JSON '%2@'. O valor de retorno esperado era '%3@', mas na verdade foi '%4@'."},
    {"ADF-MF-16223", "Nenhum ID de notifica\u00E7\u00E3o foi especificado nos argumentos"},
    {"ADF-MF-16224", "N\u00E3o foi poss\u00EDvel programar uma notifica\u00E7\u00E3o local; data inv\u00E1lida especificada"},
    {"ADF-MF-16225", "N\u00E3o foi poss\u00EDvel programar uma notifica\u00E7\u00E3o local; intervalo de repeti\u00E7\u00E3o inv\u00E1lido especificado"},
    {"ADF-MF-16226", "N\u00E3o foi poss\u00EDvel programar uma notifica\u00E7\u00E3o local; selo inv\u00E1lido especificado"},
    {"ADF-MF-16227", "N\u00E3o foi poss\u00EDvel programar uma notifica\u00E7\u00E3o local; som inv\u00E1lido especificado"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
