// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_fr extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Utilisation non valide"},
    {"ADF-MF-16004", "Cette fonction ne doit PAS \u00EAtre appel\u00E9e sur le thread principal."},
    {"ADF-MF-16022", "Argument incorrect"},
    {"ADF-MF-16023", "Un nom de package nil a \u00E9t\u00E9 transmis \u00E0 [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "Le nom de la propri\u00E9t\u00E9 ne peut pas \u00EAtre nil."},
    {"ADF-MF-16027", "Nom de classe manquant."},
    {"ADF-MF-16028", "M\u00E9thode manquante."},
    {"ADF-MF-16032", "R\u00E9ponse inattendue"},
    {"ADF-MF-16033", "La r\u00E9ponse CVM renvoy\u00E9e est nil. "},
    {"ADF-MF-16034", "La r\u00E9ponse CVM a renvoy\u00E9 un \u00E9l\u00E9ment FeatureContextAccessor nil."},
    {"ADF-MF-16035", "La r\u00E9ponse JS renvoy\u00E9e est nil."},
    {"ADF-MF-16036", "Impossible d'envoyer les appels JavaScript vers le canal '%@' sans vue Web."},
    {"ADF-MF-16074", "Message non valide"},
    {"ADF-MF-16075", "Type de message inconnu indiqu\u00E9 par le message."},
    {"ADF-MF-16092", "Format du message incorrect"},
    {"ADF-MF-16093", "Les messages de demande vides ne sont pas autoris\u00E9s."},
    {"ADF-MF-16094", "Message non pris en charge"},
    {"ADF-MF-16095", "Les messages syst\u00E8me ne sont pas pris en charge sur ce canal"},
    {"ADF-MF-16096", "Demande syst\u00E8me non valide %@"},
    {"ADF-MF-16097", "Les messages d'application ne sont pas pris en charge sur ce canal"},
    {"ADF-MF-16098", "Demande d'application non valide %@"},
    {"ADF-MF-16099", "Message non g\u00E9r\u00E9"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId : %d Type : %d Corps : %@"},
    {"ADF-MF-16101", "Message de r\u00E9ponse non sollicit\u00E9 re\u00E7u"},
    {"ADF-MF-16102", "Type de message inconnu re\u00E7u"},
    {"ADF-MF-16103", "AdfChannel.handle - Erreur lors de la gestion du message VMChannel : %@ - ERREUR : %@"},
    {"ADF-MF-16113", "La pi\u00E8ce jointe %@ est introuvable ou illisible"},
    {"ADF-MF-16115", "%@ n'est pas d\u00E9fini dans la vue Web de la fonctionnalit\u00E9 %@. Abandon de l'appel de r\u00E9sultat JavaScript."},
    {"ADF-MF-16116", "Un probl\u00E8me est survenu lors de l'appel de la fonction '%@' dans la fonctionnalit\u00E9 %@. Valeur renvoy\u00E9e : %@"},
    {"ADF-MF-16133", "Echec de l'affichage de la fonctionnalit\u00E9"},
    {"ADF-MF-16134", "Impossible d'afficher la fonctionnalit\u00E9. Echec de la tentative d'affichage de la fonctionnalit\u00E9 '%@'. ERREUR : %@"},
    {"ADF-MF-16142", "Impossible d'envoyer le message"},
    {"ADF-MF-16143", "Impossible d'envoyer un message car la messagerie textuelle n'est pas disponible sur ce dispositif."},
    {"ADF-MF-16144", "Impossible d'envoyer un message car le composeur de messages texte n'a pas pu \u00EAtre obtenu."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - Nom de classe non indiqu\u00E9"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - L'appel de morphClassName a provoqu\u00E9 une erreur : %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Echec du nom de classe morphClassName."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - M\u00E9thode non indiqu\u00E9e"},
    {"ADF-MF-16149", "Impossible de cr\u00E9er la classe : %@"},
    {"ADF-MF-16150", "Impossible de cr\u00E9er la classe demand\u00E9e \u00E0 invoquer : %@"},
    {"ADF-MF-16151", "L'instance de la classe %@ ne r\u00E9pond pas au s\u00E9lecteur '%@'."},
    {"ADF-MF-16152", "L'appel de '%@' a provoqu\u00E9 une erreur : %@"},
    {"ADF-MF-16153", "Le r\u00E9sultat de s\u00E9rialisation de '%@' sur le type %@ a provoqu\u00E9 une erreur : %@"},
    {"ADF-MF-16154", "Le r\u00E9sultat de s\u00E9rialisation de '%@' sur le type %@ a g\u00E9n\u00E9r\u00E9 une valeur nil."},
    {"ADF-MF-16156", "L'\u00E9l\u00E9ment credentialStoreKey de la connexion ne peut pas \u00EAtre nil"},
    {"ADF-MF-16189", "D\u00E9connexion"},
    {"ADF-MF-16203", "Fichier introuvable : %@"},
    {"ADF-MF-16204", "Le courriel n'a pas \u00E9t\u00E9 enregistr\u00E9 ni mis en file d'attente, probablement en raison d'une erreur."},
    {"ADF-MF-16205", "Une erreur est survenue lors de la tentative d'enregistrement du courriel dans le dossier Brouillons."},
    {"ADF-MF-16206", "Une erreur est survenue lors de la tentative de mise en file d'attente ou d'envoi du courriel."},
    {"ADF-MF-16207", "Une erreur inconnue est survenue lors de la tentative de composition ou d'envoi d'un courriel."},
    {"ADF-MF-16208", "Une erreur inconnue est survenue lors de la tentative de composition ou d'envoi d'un message texte."},
    {"ADF-MF-16209", "Fichier introuvable"},
    {"ADF-MF-16213", "L'appel de Java sur une autre fonctionnalit\u00E9 n'est pas autoris\u00E9."},
    {"ADF-MF-16214", "Violation d'acc\u00E8s"},
    {"ADF-MF-16215", "Impossible de crypter le mot de passe : %@"},
    {"ADF-MF-16216", "Impossible de g\u00E9n\u00E9rer le mot de passe via le hachage : %@"},
    {"ADF-MF-16217", "Impossible de d\u00E9crypter le mot de passe : %@"},
    {"ADF-MF-16218", "Cl\u00E9 de param\u00E8tre non valide. ParameterKey= %@"},
    {"ADF-MF-16219", "Echec de loginComplete avec l'exception : %@"},
    {"ADF-MF-16220", "Impossible de d\u00E9terminer le type de donn\u00E9es renvoy\u00E9 de la classe %@ pour la m\u00E9thode %@."},
    {"ADF-MF-16221", "Type de donn\u00E9es renvoy\u00E9 non valide pour la m\u00E9thode %@ dans la classe %@."},
    {"ADF-MF-16222", "Un probl\u00E8me est survenu lors de la remise des \u00E9v\u00E9nements de modification de donn\u00E9es \u00E0 la fonctionnalit\u00E9 '%1@' avec les donn\u00E9es trait\u00E9es JSON '%2@'. Valeur renvoy\u00E9e attendue : '%3@'. Valeur r\u00E9ellement renvoy\u00E9e : '%4@'."},
    {"ADF-MF-16223", "Aucun ID de notification n'est indiqu\u00E9 dans les arguments"},
    {"ADF-MF-16224", "Impossible de programmer une notification locale, car la date indiqu\u00E9e n'est pas valide"},
    {"ADF-MF-16225", "Impossible de programmer une notification locale, car l'intervalle de r\u00E9p\u00E9tition indiqu\u00E9 n'est pas valide"},
    {"ADF-MF-16226", "Impossible de programmer une notification locale, car la date indiqu\u00E9e n'est pas valide"},
    {"ADF-MF-16227", "Impossible de programmer une notification locale, car le son indiqu\u00E9 n'est pas valide"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
