// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_de extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Ung\u00FCltige Verwendung"},
    {"ADF-MF-16004", "Diese Funktion darf NICHT auf dem Hauptthread aufgerufen werden."},
    {"ADF-MF-16022", "Ung\u00FCltiges Argument"},
    {"ADF-MF-16023", "Es wurde ein Null-Packagename an [oraADFLogger getLogger:] \u00FCbergeben."},
    {"ADF-MF-16025", "Eigenschaftsname darf nicht null sein."},
    {"ADF-MF-16027", "Fehlender Klassenname."},
    {"ADF-MF-16028", "Fehlende Methode."},
    {"ADF-MF-16032", "Unerwartete Antwort"},
    {"ADF-MF-16033", "CVM-Antwort hat einen Nullwert zur\u00FCckgegeben. "},
    {"ADF-MF-16034", "CVM-Antwort hat einen Nullwert f\u00FCr FeatureContextAccessor zur\u00FCckgegeben."},
    {"ADF-MF-16035", "JS-Antwort hat einen Nullwert zur\u00FCckgegeben."},
    {"ADF-MF-16036", "JavaScript-Aufrufe k\u00F6nnen nicht zu Kanal \"%@\" gesendet werden, der keine Webansicht besitzt."},
    {"ADF-MF-16074", "Ung\u00FCltige Nachricht"},
    {"ADF-MF-16075", "Unbekannter Nachrichtentyp von Nachricht angegeben."},
    {"ADF-MF-16092", "Fehlerhafte Nachricht"},
    {"ADF-MF-16093", "Leere Anforderungsnachricht ist nicht zul\u00E4ssig."},
    {"ADF-MF-16094", "Nicht unterst\u00FCtzte Meldung"},
    {"ADF-MF-16095", "Systemmeldungen werden auf diesem Kanal nicht unterst\u00FCtzt"},
    {"ADF-MF-16096", "Ung\u00FCltige Systemanforderung %@"},
    {"ADF-MF-16097", "Anwendungsmeldungen werden auf diesem Kanal nicht unterst\u00FCtzt"},
    {"ADF-MF-16098", "Ung\u00FCltige Anwendungsanforderung %@"},
    {"ADF-MF-16099", "Nicht verarbeitete Meldung"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Typ: %d Body: %@"},
    {"ADF-MF-16101", "Eine nicht abgerufene Antwortnachricht wurde empfangen"},
    {"ADF-MF-16102", "Ein unbekannter Nachrichtentyp wurde empfangen"},
    {"ADF-MF-16103", "AdfChannel.handle - Fehler beim Verarbeiten der VMChannel-Meldung: %@ - FEHLER: %@"},
    {"ADF-MF-16113", "Anhang %@ wurde nicht gefunden oder konnte nicht gelesen werden"},
    {"ADF-MF-16115", "%@ ist in der Webview f\u00FCr Feature %@ nicht definiert. JavaScript-Ergebnisaufruf abgebrochen."},
    {"ADF-MF-16116", "Beim Aufrufen der Funktion \"%@\" in Feature %@ ist ein Problem aufgetreten. Zur\u00FCckgegebener Wert: %@"},
    {"ADF-MF-16133", "Anzeigen des Features nicht erfolgreich"},
    {"ADF-MF-16134", "Feature konnte nicht angezeigt werden. Versuch, das Feature '%@' anzuzeigen, war nicht erfolgreich. FEHLER: %@"},
    {"ADF-MF-16142", "Nachricht kann nicht gesendet werden"},
    {"ADF-MF-16143", "Nachricht kann nicht gesendet werden, da mit diesem Ger\u00E4t keine SMS m\u00F6glich sind."},
    {"ADF-MF-16144", "Nachricht kann nicht gesendet werden, da der Textnachrichten-Composer nicht abgerufen werden kann."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - Der \"Klassenname\" wurde nicht angegeben"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - Der morphClassName-Aufruf hat einen FEHLER verursacht: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Der \"Klassenname\" morphClassName war nicht erfolgreich."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - Die \"Methode\" wurde nicht angegeben"},
    {"ADF-MF-16149", "Klasse konnte nicht erstellt werden: %@"},
    {"ADF-MF-16150", "Zum Aufruf angeforderte Klasse konnte nicht erstellt werden: %@"},
    {"ADF-MF-16151", "Instanz von %@-Klasse reagiert nicht auf \"%@\"-Selektor."},
    {"ADF-MF-16152", "Aufruf von \"%@\" hat einen Fehler verursacht: %@"},
    {"ADF-MF-16153", "Serialisieren des Ergebnisses von \"%@\" auf Typ %@ hat einen FEHLER verursacht: %@"},
    {"ADF-MF-16154", "Serialisieren des Ergebnisses von \"%@\" auf Typ %@ hat nichts generiert."},
    {"ADF-MF-16156", "credentialStoreKey f\u00FCr Verbindung darf nicht Null sein"},
    {"ADF-MF-16189", "Abmelden"},
    {"ADF-MF-16203", "Datei nicht gefunden: %@"},
    {"ADF-MF-16204", "Die E-Mail-Nachricht wurde m\u00F6glicherweise aufgrund eines Fehlers nicht gespeichert oder in die Queue gestellt."},
    {"ADF-MF-16205", "Beim Versuch, die E-Mail-Nachricht im Entwurfsordner zu speichern, ist ein Fehler aufgetreten."},
    {"ADF-MF-16206", "Beim Versuch, die E-Mail-Nachricht in die Queue zu stellen oder zu senden, ist ein Fehler aufgetreten."},
    {"ADF-MF-16207", "Beim Versuch, eine E-Mail zu verfassen oder zu senden, ist ein unbekannter Fehler aufgetreten"},
    {"ADF-MF-16208", "Beim Versuch, eine SMS zu verfassen oder zu senden, ist ein unbekannter Fehler aufgetreten"},
    {"ADF-MF-16209", "Datei nicht gefunden"},
    {"ADF-MF-16213", "Aufruf von \"Java aufrufen\" bei anderem Feature wird nicht unterst\u00FCtzt."},
    {"ADF-MF-16214", "Zugriffsverletzung"},
    {"ADF-MF-16215", "Kennwort kann nicht verschl\u00FCsselt werden: %@"},
    {"ADF-MF-16216", "Kennwort kann per Hashing nicht erstellt werden: %@"},
    {"ADF-MF-16217", "Kennwort kann nicht entschl\u00FCsselt werden: %@"},
    {"ADF-MF-16218", "Ung\u00FCltiger Parameterschl\u00FCssel. ParameterKey= %@"},
    {"ADF-MF-16219", "loginComplete nicht erfolgreich mit Exception: %@"},
    {"ADF-MF-16220", "R\u00FCckgabetyp der Klasse %@ f\u00FCr Methode %@ konnte nicht bestimmt werden."},
    {"ADF-MF-16221", "Ung\u00FCltiger R\u00FCckgabetyp f\u00FCr Methode %@ in Klasse %@."},
    {"ADF-MF-16222", "Beim Zustellen der Daten\u00E4nderungsereignisse an Feature \"%1@\" mit JSON-Payload \"%2@\" ist ein Problem aufgetreten. R\u00FCckgabewert \"%3@\" wurde erwartet, war jedoch \"%4@\"."},
    {"ADF-MF-16223", "Keine Benachrichtigungs-ID in Argumenten angegeben"},
    {"ADF-MF-16224", "Lokale Benachrichtigung kann nicht geplant werden. Ung\u00FCltiges Datum angegeben"},
    {"ADF-MF-16225", "Lokale Benachrichtigung kann nicht geplant werden. Ung\u00FCltiges Wiederholungsintervall angegeben"},
    {"ADF-MF-16226", "Lokale Benachrichtigung kann nicht geplant werden. Ung\u00FCltiges Badge angegeben"},
    {"ADF-MF-16227", "Lokale Benachrichtigung kann nicht geplant werden. Ung\u00FCltiges akustisches Signal angegeben"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
