// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_nl extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Ongeldig gebruik"},
    {"ADF-MF-16004", "Deze functie mag NIET worden aangeroepen in de hoofdthread."},
    {"ADF-MF-16022", "Ongeldig argument"},
    {"ADF-MF-16023", "Er is een nul-pakketnaam doorgegeven aan [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "De naam van een eigenschap mag niet nul zijn."},
    {"ADF-MF-16027", "Ontbrekende klassennaam"},
    {"ADF-MF-16028", "Ontbrekende methode"},
    {"ADF-MF-16032", "Onverwachte respons"},
    {"ADF-MF-16033", "Door CVM-respons is een nul-respons geretourneerd. "},
    {"ADF-MF-16034", "Door CVM-respons is een nul-FeatureContextAccessor geretourneerd."},
    {"ADF-MF-16035", "Door JS-respons is een nul-respons geretourneerd."},
    {"ADF-MF-16036", "JavaScript-aanroepen kunnen niet worden verstuurd naar het kanaal '%@' dat geen webview heeft."},
    {"ADF-MF-16074", "Ongeldig bericht"},
    {"ADF-MF-16075", "Ongeldig berichttype opgegeven door bericht."},
    {"ADF-MF-16092", "Onjuist bericht"},
    {"ADF-MF-16093", "Leeg aanvraagbericht is niet toegestaan."},
    {"ADF-MF-16094", "Niet-ondersteund bericht"},
    {"ADF-MF-16095", "Systeemberichten worden niet ondersteund in dit kanaal."},
    {"ADF-MF-16096", "Ongeldige systeemaanvraag %@"},
    {"ADF-MF-16097", "Applicatieberichten worden niet ondersteund in dit kanaal."},
    {"ADF-MF-16098", "Ongeldige applicatieaanvraag %@"},
    {"ADF-MF-16099", "Niet-afgehandeld bericht"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Type: %d Body: %@"},
    {"ADF-MF-16101", "Ongevraagd responsbericht ontvangen"},
    {"ADF-MF-16102", "Onbekend berichttype ontvangen"},
    {"ADF-MF-16103", "AdfChannel.handle - Fout bij afhandelen VMChannel-bericht: %@ - FOUT: %@"},
    {"ADF-MF-16113", "Bijlage %@ is niet gevonden of kan niet worden gelezen."},
    {"ADF-MF-16115", "%@ is niet gedefinieerd in de webweergave voor functionaliteit %@. JavaScript-resultaataanroep is afgebroken."},
    {"ADF-MF-16116", "Er is een probleem opgetreden bij het aanroepen van de functie '%@' in functionaliteit %@. Resultaatwaarde: %@"},
    {"ADF-MF-16133", "Tonen van functionaliteit is mislukt."},
    {"ADF-MF-16134", "Functionaliteit kan niet worden getoond. Poging om functionaliteit '%@' te tonen is mislukt. FOUT: %@"},
    {"ADF-MF-16142", "Bericht kan niet worden verstuurd."},
    {"ADF-MF-16143", "Bericht kan niet worden verstuurd omdat tekstberichten niet beschikbaar zijn op dit apparaat."},
    {"ADF-MF-16144", "Bericht kan niet worden verstuurd. Composer voor tekstbericht ophalen is niet mogelijk."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest: de 'klassennaam' is niet opgegeven."},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest: de oproep morphClassName heeft een FOUT veroorzaakt: %@."},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest: de 'klassennaam' morphClassName is mislukt."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest: de 'methode' is niet opgegeven."},
    {"ADF-MF-16149", "Klasse kan niet worden aangemaakt: %@."},
    {"ADF-MF-16150", "Aangevraagde op te roepen klasse kan niet worden aangemaakt: %@."},
    {"ADF-MF-16151", "Instance van klasse %@ beantwoordt selector '%@' niet."},
    {"ADF-MF-16152", "Aanroepen van '%@' heeft fout veroorzaakt: %@."},
    {"ADF-MF-16153", "Resultaat van '%@' serialiseren op type %@ heeft FOUT veroorzaakt: %@."},
    {"ADF-MF-16154", "Resultaat van '%@' serialiseren op type %@ heeft nil gegenereerd."},
    {"ADF-MF-16156", "credentialStoreKey voor verbinding kan niet nil zijn."},
    {"ADF-MF-16189", "Uitloggen"},
    {"ADF-MF-16203", "Bestand niet gevonden: %@"},
    {"ADF-MF-16204", "Het e-mailbericht is niet opgeslagen of in een wachtrij gezet, mogelijk als gevolg van een fout."},
    {"ADF-MF-16205", "Er is een fout opgetreden bij het opslaan van het e-mailbericht in de map 'Concepten'."},
    {"ADF-MF-16206", "Er is een fout opgetreden bij het in de wachtrij zetten of versturen van het e-mailbericht."},
    {"ADF-MF-16207", "Er is een onbekende fout opgetreden bij het opstellen of versturen van een e-mail."},
    {"ADF-MF-16208", "Er is een onbekende fout opgetreden bij het opstellen of versturen van een tekstbericht."},
    {"ADF-MF-16209", "Bestand niet gevonden."},
    {"ADF-MF-16213", "Aanroepen van Java-oproep voor andere functionaliteit is niet toegestaan."},
    {"ADF-MF-16214", "Schending van toegangsrecht"},
    {"ADF-MF-16215", "Wachtwoord kan niet worden gecodeerd: %@."},
    {"ADF-MF-16216", "Wachtwoord kan niet worden gegenereerd via hashing: %@."},
    {"ADF-MF-16217", "Wachtwoord kan niet worden gedecodeerd: %@."},
    {"ADF-MF-16218", "Ongeldige parametersleutel. ParameterKey= %@."},
    {"ADF-MF-16219", "loginComplete is mislukt met uitzondering: %@"},
    {"ADF-MF-16220", "Het retourtype van klasse %@ kan niet worden vastgesteld voor methode %@."},
    {"ADF-MF-16221", "Ongeldig retourtype voor methode %@ in klasse %@."},
    {"ADF-MF-16222", "Er is een probleem opgetreden bij het afleveren van de gegevenswijzigingsevents voor functionaliteit '%1@' met JSON payload '%2@'. De verwachte resultaatwaarde is '%3@', maar de werkelijke waarde is '%4@'."},
    {"ADF-MF-16223", "Er is geen meldings-ID opgegeven in argumenten."},
    {"ADF-MF-16224", "Er kan geen lokale melding worden gepland. De opgegeven datum is ongeldig."},
    {"ADF-MF-16225", "Er kan geen lokale melding worden gepland. Het opgegeven herhalingsinterval is ongeldig."},
    {"ADF-MF-16226", "Er kan geen lokale melding worden gepland. De opgegeven badge is ongeldig."},
    {"ADF-MF-16227", "Er kan geen lokale melding worden gepland. Het opgegeven geluid is ongeldig."},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
