// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_pl extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Niepoprawne u\u017Cycie"},
    {"ADF-MF-16004", "Ta funkcja NIE mo\u017Ce zosta\u0107 wywo\u0142ana w w\u0105tku g\u0142\u00F3wnym."},
    {"ADF-MF-16022", "Niepoprawny argument"},
    {"ADF-MF-16023", "Do [oraADFLogger getLogger:] przekazano nazw\u0119 pakietu o warto\u015Bci nil."},
    {"ADF-MF-16025", "Nazwa w\u0142a\u015Bciwo\u015Bci nie mo\u017Ce mie\u0107 warto\u015Bci nil."},
    {"ADF-MF-16027", "Brak nazwy klasy."},
    {"ADF-MF-16028", "Brak metody."},
    {"ADF-MF-16032", "Nieoczekiwana odpowied\u017A"},
    {"ADF-MF-16033", "Odpowied\u017A CVM mia\u0142a warto\u015B\u0107 nil. "},
    {"ADF-MF-16034", "Odpowied\u017A CVM zwr\u00F3ci\u0142a FeatureContextAccessor o warto\u015Bci nil."},
    {"ADF-MF-16035", "Odpowied\u017A JS mia\u0142a warto\u015B\u0107 nil."},
    {"ADF-MF-16036", "Nie mo\u017Cna wysy\u0142a\u0107 wywo\u0142a\u0144 JavaScript do kana\u0142u \"%@\", kt\u00F3ry nie ma sk\u0142adnika WebView."},
    {"ADF-MF-16074", "Niepoprawny komunikat"},
    {"ADF-MF-16075", "W komunikacie jest okre\u015Blony niepoprawny typ komunikatu."},
    {"ADF-MF-16092", "Niepoprawna posta\u0107 komunikatu"},
    {"ADF-MF-16093", "Pusty komunikat \u017C\u0105dania jest niedozwolony."},
    {"ADF-MF-16094", "Nieobs\u0142ugiwany komunikat"},
    {"ADF-MF-16095", "Komunikaty systemu nie s\u0105 obs\u0142ugiwane przez ten kana\u0142"},
    {"ADF-MF-16096", "Niepoprawne \u017C\u0105danie systemu: %@"},
    {"ADF-MF-16097", "Komunikaty aplikacji nie s\u0105 obs\u0142ugiwane przez ten kana\u0142"},
    {"ADF-MF-16098", "Niepoprawne \u017C\u0105danie aplikacji: %@"},
    {"ADF-MF-16099", "Nieobs\u0142ugiwany komunikat"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ID odwo\u0142ania: %d, typ: %d, tre\u015B\u0107: %@"},
    {"ADF-MF-16101", "Otrzymano niezam\u00F3wiony komunikat-odpowied\u017A"},
    {"ADF-MF-16102", "Otrzymano nieznany typ komunikatu"},
    {"ADF-MF-16103", "AdfChannel.handle - B\u0142\u0105d podczas obs\u0142ugi komunikatu VMChannel: %@ - B\u0141\u0104D: %@"},
    {"ADF-MF-16113", "Nie znaleziono za\u0142\u0105cznika %@ lub nie mo\u017Cna by\u0142o go odczyta\u0107"},
    {"ADF-MF-16115", "%@ nie jest zdef. w widoku internetowym dla funkcji %@. Wywo\u0142anie wyniku skryptu JavaScript zosta\u0142o przerwane."},
    {"ADF-MF-16116", "Wyst\u0105pi\u0142 problem podczas wywo\u0142ywania funkcji \"%@\" w funkcji %@. Zwr\u00F3cono warto\u015B\u0107: %@"},
    {"ADF-MF-16133", "Nie uda\u0142o si\u0119 pokaza\u0107 funkcji"},
    {"ADF-MF-16134", "Nie uda\u0142o si\u0119 pokaza\u0107 funkcji. Pr\u00F3ba pokazania funkcji \"%@\" zako\u0144czy\u0142a si\u0119 niepowodzeniem. B\u0141\u0104D: %@"},
    {"ADF-MF-16142", "Nie mo\u017Cna wys\u0142a\u0107 wiadomo\u015Bci"},
    {"ADF-MF-16143", "Nie mo\u017Cna wys\u0142a\u0107 wiadomo\u015Bci, poniewa\u017C us\u0142uga tekstowa nie jest dost\u0119pna w tym urz\u0105dzenia."},
    {"ADF-MF-16144", "Nie mo\u017Cna wys\u0142a\u0107 wiadomo\u015Bci, poniewa\u017C nie mo\u017Cna uzyska\u0107 procesu Composer wiadomo\u015Bci tekstowej."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - Nie podano parametru 'classname'"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - Wywo\u0142anie morphClassName spowodowa\u0142o b\u0142\u0105d: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Niepowodzenie wywo\u0142ania morphClassName 'classname'."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - Nie podano parametru 'method'"},
    {"ADF-MF-16149", "Nie mo\u017Cna utworzy\u0107 klasy: %@"},
    {"ADF-MF-16150", "Nie mo\u017Cna utworzy\u0107 \u017C\u0105danej, wywo\u0142ywanej klasy: %@"},
    {"ADF-MF-16151", "Instancja klasy %@ nie odpowiada selektorowi \"%@\"."},
    {"ADF-MF-16152", "Wywo\u0142anie \"%@\" spowodowa\u0142o b\u0142\u0105d: %@"},
    {"ADF-MF-16153", "Serializacja wyniku z \"%@\" przy typie %@ spowodowa\u0142a b\u0142\u0105d: %@"},
    {"ADF-MF-16154", "Serializacja wyniku z \"%@\" przy typie %@ da\u0142a w wyniku warto\u015B\u0107 nil."},
    {"ADF-MF-16156", "credentialStoreKey dla po\u0142\u0105czenia nie mo\u017Ce mie\u0107 warto\u015Bci nil"},
    {"ADF-MF-16189", "Wylogowywanie"},
    {"ADF-MF-16203", "Nie znaleziono pliku: %@"},
    {"ADF-MF-16204", "Wiadomo\u015B\u0107 e-mail nie zosta\u0142a zapisana ani zakolejkowana, prawdopodobnie wskutek b\u0142\u0119du."},
    {"ADF-MF-16205", "Wyst\u0105pi\u0142 b\u0142\u0105d podczas pr\u00F3by zapisania widomo\u015Bci e-mail w folderze \"Wersje robocze\"."},
    {"ADF-MF-16206", "Wyst\u0105pi\u0142 b\u0142\u0105d podczas pr\u00F3by zakolejkowania lub wys\u0142ania wiadomo\u015Bci e-mail."},
    {"ADF-MF-16207", "Wyst\u0105pi\u0142 nieznany b\u0142\u0105d podczas pr\u00F3by utworzenia lub wys\u0142ania wiadomo\u015Bci e-mail."},
    {"ADF-MF-16208", "Wyst\u0105pi\u0142 nieznany b\u0142\u0105d podczas pr\u00F3by utworzenia lub wys\u0142ania wiadomo\u015Bci tekstowej."},
    {"ADF-MF-16209", "Nie znaleziono pliku"},
    {"ADF-MF-16213", "Wywo\u0142anie Javy dla innej funkcji nie jest dozwolone."},
    {"ADF-MF-16214", "Naruszenie zasad dost\u0119pu"},
    {"ADF-MF-16215", "Nie mo\u017Cna zaszyfrowa\u0107 has\u0142a: %@"},
    {"ADF-MF-16216", "Nie mo\u017Cna wygenerowa\u0107 has\u0142a za pomoc\u0105 haszowania: %@"},
    {"ADF-MF-16217", "Nie mo\u017Cna odszyfrowa\u0107 has\u0142a: %@"},
    {"ADF-MF-16218", "Niepoprawny klucz parametru. ParameterKey= %@"},
    {"ADF-MF-16219", "Niepowodzenie loginComplete - wyj\u0105tek: %@"},
    {"ADF-MF-16220", "Nie mo\u017Cna by\u0142o ustali\u0107 typu zwrotnego klasy %@ dla metody %@."},
    {"ADF-MF-16221", "Niepoprawny typ zwrotny dla metody %@ z klasy %@."},
    {"ADF-MF-16222", "Wyst\u0105pi\u0142 problem podczas dostarczania zdarze\u0144 zmiany danych do funkcji \"%1@\" z \u0142adunkiem JSON \"%2@\". Oczekiwano zwracanej warto\u015Bci \"%3@\", lecz uzyskano \"%4@\"."},
    {"ADF-MF-16223", "W argumentach nie podano ID powiadomienia"},
    {"ADF-MF-16224", "Nie mo\u017Cna zaplanowa\u0107 powiadomienia lokalnego; podano niepoprawn\u0105 dat\u0119"},
    {"ADF-MF-16225", "Nie mo\u017Cna zaplanowa\u0107 powiadomienia lokalnego; podano niepoprawny interwa\u0142 powtarzania"},
    {"ADF-MF-16226", "Nie mo\u017Cna zaplanowa\u0107 powiadomienia lokalnego; podano niepoprawn\u0105 odznak\u0119"},
    {"ADF-MF-16227", "Nie mo\u017Cna zaplanowa\u0107 powiadomienia lokalnego; podano niepoprawny d\u017Awi\u0119k"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
