// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_da extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Ugyldig brug"},
    {"ADF-MF-16004", "Denne funktion m\u00E5 IKKE kaldes i hovedtr\u00E5den."},
    {"ADF-MF-16022", "Ugyldigt argument"},
    {"ADF-MF-16023", "Et nulpakkenavn blev videregivet til [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "Egenskabsnavn kan ikke v\u00E6re nul."},
    {"ADF-MF-16027", "Manglende klassenavn."},
    {"ADF-MF-16028", "Manglende metode."},
    {"ADF-MF-16032", "Uventet svar"},
    {"ADF-MF-16033", "CVM-svar returnerede et nulsvar. "},
    {"ADF-MF-16034", "CVM-svar returnerede en nul-FeatureContextAccessor."},
    {"ADF-MF-16035", "JS-svar returnerede et nulsvar."},
    {"ADF-MF-16036", "Kan ikke sende JavaScript-kald til kanalen '%@', som ikke har en webvisning."},
    {"ADF-MF-16074", "Ugyldig meddelelse"},
    {"ADF-MF-16075", "Ukendt meddelelsestype blev angivet af meddelelse."},
    {"ADF-MF-16092", "Forkert udformet meddelelse"},
    {"ADF-MF-16093", "Tom anmodningsmeddelelse er ikke tilladt."},
    {"ADF-MF-16094", "Ikke-underst\u00F8ttet meddelelse"},
    {"ADF-MF-16095", "Systemmeddelelser underst\u00F8ttes ikke p\u00E5 denne kanal"},
    {"ADF-MF-16096", "Ugyldig systemanmodning %@"},
    {"ADF-MF-16097", "Applikationsmeddelelser underst\u00F8ttes ikke p\u00E5 denne kanal"},
    {"ADF-MF-16098", "Ugyldig applikationsanmodning %@"},
    {"ADF-MF-16099", "Ikke-h\u00E5ndteret meddelelse"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Type: %d Indhold: %@"},
    {"ADF-MF-16101", "Modtog en uanmodet svarmeddelelse"},
    {"ADF-MF-16102", "Modtog en ukendt meddelelsestype"},
    {"ADF-MF-16103", "AdfChannel.handle - Fejl under h\u00E5ndtering af VMChannel-meddelelsen: %@ - FEJL: %@"},
    {"ADF-MF-16113", "Den vedh\u00E6ftede fil %@ blev ikke fundet eller kunne ikke l\u00E6ses"},
    {"ADF-MF-16115", "%@ er ikke defineret i webvisningen for faciliteten %@. Kald af JavaScript-resultat blev afbrudt."},
    {"ADF-MF-16116", "Der var problemer med at kalde funktionen '%@' i faciliteten %@. Returneret v\u00E6rdi: %@"},
    {"ADF-MF-16133", "Visning af facilitet fejlede"},
    {"ADF-MF-16134", "Kunne ikke vise facilitet. Fors\u00F8g p\u00E5 at vise faciliteten '%@' fejlede. FEJL: %@"},
    {"ADF-MF-16142", "Kan ikke sende meddelelse"},
    {"ADF-MF-16143", "Kunne ikke sende meddelelse, da tekstmeddelelser ikke er tilg\u00E6ngelige p\u00E5 denne enhed."},
    {"ADF-MF-16144", "Kan ikke sende meddelelse, da tekstmeddelelsesopretter ikke kan hentes."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - 'klassenavn' blev ikke angivet"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - morphClassName-kaldet for\u00E5rsagede en FEJL: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - 'klassenavnet' morphClassName fejlede."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - 'metode' blev ikke angivet"},
    {"ADF-MF-16149", "Kunne ikke oprette klasse: %@"},
    {"ADF-MF-16150", "Den klasse, der skulle kaldes, kunne ikke oprettes: %@"},
    {"ADF-MF-16151", "Instans af klassen %@ svarer ikke p\u00E5 v\u00E6lgeren '%@'."},
    {"ADF-MF-16152", "Kald af '%@' for\u00E5rsagede fejl: %@"},
    {"ADF-MF-16153", "Serialisering af resultat fra '%@' i typen %@ for\u00E5rsagede FEJL: %@"},
    {"ADF-MF-16154", "Serialisering af resultat fra '%@' i typen %@ genererede nul."},
    {"ADF-MF-16156", "credentialStoreKey for forbindelse kan ikke v\u00E6re nul"},
    {"ADF-MF-16189", "Logoff"},
    {"ADF-MF-16203", "Fil blev ikke fundet: %@"},
    {"ADF-MF-16204", "E-mail-meddelelsen blev ikke sendt eller sat i k\u00F8, muligvis p\u00E5 grund af en fejl."},
    {"ADF-MF-16205", "En fejl opstod under fors\u00F8g p\u00E5 at gemme e-mail-meddelelsen i mappen Kladder."},
    {"ADF-MF-16206", "En fejl opstod under fors\u00F8g p\u00E5 at sende eller s\u00E6tte e-mail-meddelelsen i k\u00F8."},
    {"ADF-MF-16207", "En ukendt fejl opstod under fors\u00F8g p\u00E5 at oprette eller sende en e-mail"},
    {"ADF-MF-16208", "En ukendt fejl opstod under fors\u00F8g p\u00E5 at oprette eller sende en tekstmeddelelse"},
    {"ADF-MF-16209", "Fil blev ikke fundet"},
    {"ADF-MF-16213", "Kald af Java i en anden facilitet er ikke tilladt."},
    {"ADF-MF-16214", "Adgangsfejl"},
    {"ADF-MF-16215", "Kan ikke kryptere adgangskoden: %@"},
    {"ADF-MF-16216", "Kan ikke generere adgangskode via hashing: %@"},
    {"ADF-MF-16217", "Kan ikke dekryptere adgangskoden: %@"},
    {"ADF-MF-16218", "Ugyldig parametern\u00F8gle. ParameterKey= %@"},
    {"ADF-MF-16219", "loginComplete fejlede med undtagelsen: %@"},
    {"ADF-MF-16220", "Kunne ikke bestemme returtypen i klassen %@ for metoden %@."},
    {"ADF-MF-16221", "Ugyldig returtype for metoden %@ i klassen %@."},
    {"ADF-MF-16222", "Der var problemer med at levere data\u00E6ndringsbegivenheder til faciliteten '%1@' med JSON-payload '%2@'. Forventet returv\u00E6rdi '%3@', men var '%4@'."},
    {"ADF-MF-16223", "Intet besked-ID er angivet i argumenter"},
    {"ADF-MF-16224", "Kan ikke planl\u00E6gge en lokal besked. Den angivne dato er ugyldig"},
    {"ADF-MF-16225", "Kan ikke planl\u00E6gge en lokal besked. Det angivne gentagelsesinterval er ugyldigt"},
    {"ADF-MF-16226", "Kan ikke planl\u00E6gge en lokal besked. Det angivne badge er ugyldigt"},
    {"ADF-MF-16227", "Kan ikke planl\u00E6gge en lokal besked. Den angivne lyd er ugyldig"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
