// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_fi extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Virheellinen k\u00E4ytt\u00F6"},
    {"ADF-MF-16004", "T\u00E4t\u00E4 funktiota EI saa kutsua p\u00E4\u00E4s\u00E4ikeess\u00E4."},
    {"ADF-MF-16022", "Argumentti ei kelpaa"},
    {"ADF-MF-16023", "Tyhj\u00E4 paketin nimi v\u00E4litettiin kohteeseen [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "Ominaisuuden nimi ei voi olla tyhj\u00E4."},
    {"ADF-MF-16027", "Puuttuva luokkanimi."},
    {"ADF-MF-16028", "Puuttuva menetelm\u00E4."},
    {"ADF-MF-16032", "Odottamaton vastaus"},
    {"ADF-MF-16033", "CVM Response palautti tyhj\u00E4n vastauksen. "},
    {"ADF-MF-16034", "CVM Response palautti tyhj\u00E4n kohteen FeatureContextAccessor."},
    {"ADF-MF-16035", "JS Response palautti tyhj\u00E4n vastauksen."},
    {"ADF-MF-16036", "Ei voi l\u00E4hett\u00E4\u00E4 JavaScript-kutsuja kanavalle %@, jolla ei ole Web-n\u00E4kym\u00E4\u00E4."},
    {"ADF-MF-16074", "Virheellinen sanoma"},
    {"ADF-MF-16075", "Sanomassa m\u00E4\u00E4ritetty tuntematon sanomatyyppi."},
    {"ADF-MF-16092", "V\u00E4\u00E4rin muodostettu sanoma"},
    {"ADF-MF-16093", "Tyhj\u00E4\u00E4 pyynt\u00F6sanomaa ei sallita."},
    {"ADF-MF-16094", "Sanomaa ei tueta"},
    {"ADF-MF-16095", "J\u00E4rjestelm\u00E4sanomia ei tueta t\u00E4ss\u00E4 kanavassa"},
    {"ADF-MF-16096", "Virheellinen j\u00E4rjestelm\u00E4pyynt\u00F6 %@"},
    {"ADF-MF-16097", "Sovellussanomia ei tueta t\u00E4ss\u00E4 kanavassa"},
    {"ADF-MF-16098", "Virheellinen sovelluspyynt\u00F6 %@"},
    {"ADF-MF-16099", "K\u00E4sittelem\u00E4t\u00F6n sanoma"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d tyyppi: %d runko: %@"},
    {"ADF-MF-16101", "Vastaanotettiin ei-pyydetty vastaussanoma"},
    {"ADF-MF-16102", "Vastaanotettiin tuntematon sanomatyyppi"},
    {"ADF-MF-16103", "AdfChannel.handle - virhe VMChannel-sanoman k\u00E4sittelyss\u00E4: %@ - VIRHE: %@"},
    {"ADF-MF-16113", "Liitett\u00E4 %@ ei l\u00F6ytynyt tai sit\u00E4 ei voi lukea"},
    {"ADF-MF-16115", "Kohdetta %@ ei ole m\u00E4\u00E4ritetty web-n\u00E4kym\u00E4ss\u00E4 ominaisuudelle %@. JavaScript-tuloksen kutsu keskeytetty."},
    {"ADF-MF-16116", "Ongelma kutsuttaessa funktiota %@ ominaisuudessa %@. Palautettu arvo: %@"},
    {"ADF-MF-16133", "Ominaisuuden n\u00E4ytt\u00E4minen ep\u00E4onnistui"},
    {"ADF-MF-16134", "Ominaisuutta ei voitu n\u00E4ytt\u00E4\u00E4. Yritys n\u00E4ytt\u00E4\u00E4 ominaisuus %@ ep\u00E4onnistui.  VIRHE: %@"},
    {"ADF-MF-16142", "Sanomaa ei voi l\u00E4hett\u00E4\u00E4"},
    {"ADF-MF-16143", "Sanomaa ei voi l\u00E4hett\u00E4\u00E4, sill\u00E4 tekstiviestit eiv\u00E4t ole k\u00E4ytett\u00E4viss\u00E4 t\u00E4ss\u00E4 laitteessa."},
    {"ADF-MF-16144", "Sanomaa ei voi l\u00E4hett\u00E4\u00E4, koska tekstiviestien luontiohjelmaa ei voi hakea."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - luokkanime\u00E4 ei m\u00E4\u00E4ritetty"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - morphClassName-kutsu aiheutti VIRHEEN: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - luokkanimi morphClassName ep\u00E4onnistui."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - menetelm\u00E4\u00E4 ei m\u00E4\u00E4ritetty"},
    {"ADF-MF-16149", "Luokkaa ei voi luoda: %@"},
    {"ADF-MF-16150", "Kutsuttavaksi pyydetty\u00E4 luokkaa ei voitu luoda: %@"},
    {"ADF-MF-16151", "Luokan %@ instanssi ei vastaa valitsimelle %@."},
    {"ADF-MF-16152", "Kohteen %@ kutsu aiheutti virheen: %@"},
    {"ADF-MF-16153", "Kohteen %@ tuloksen sarjoitus tyypiss\u00E4 %@ aiheutti VIRHEEN: %@"},
    {"ADF-MF-16154", "Kohteen %@ tuloksen sarjoitus tyypiss\u00E4 %@ tuotti tyhj\u00E4n."},
    {"ADF-MF-16156", "Yhteyden credentialStoreKey ei voi olla tyhj\u00E4"},
    {"ADF-MF-16189", "Kirjaudu ulos"},
    {"ADF-MF-16203", "Tiedostoa ei l\u00F6ydy: %@"},
    {"ADF-MF-16204", "S\u00E4hk\u00F6postiviesti\u00E4 ei tallennettu tai siirretty jonoon todenn\u00E4k\u00F6isesti virheen vuoksi."},
    {"ADF-MF-16205", "Virhe tallennettaessa s\u00E4hk\u00F6postiviesti\u00E4 luonnosten kansioon."},
    {"ADF-MF-16206", "Virhe l\u00E4hetett\u00E4ess\u00E4 s\u00E4hk\u00F6postiviesti\u00E4 tai siirrett\u00E4ess\u00E4 sit\u00E4 jonoon."},
    {"ADF-MF-16207", "Tuntematon virhe luotaessa tai l\u00E4hetett\u00E4ess\u00E4 s\u00E4hk\u00F6postiviesti\u00E4"},
    {"ADF-MF-16208", "Tuntematon virhe luotaessa tai l\u00E4hetett\u00E4ess\u00E4 tekstiviesti\u00E4"},
    {"ADF-MF-16209", "Tiedostoa ei l\u00F6ydy"},
    {"ADF-MF-16213", "Javan kutsuminen ei ole sallittu toisessa ominaisuudessa."},
    {"ADF-MF-16214", "K\u00E4ytt\u00F6oikeusrikkomus"},
    {"ADF-MF-16215", "Ei voi salata salasanaa: %@"},
    {"ADF-MF-16216", "Salasanaa ei voi luoda hajauttamalla: %@"},
    {"ADF-MF-16217", "Ei voi purkaa salasanan salausta: %@"},
    {"ADF-MF-16218", "Virheellinen parametrin avain. ParameterKey= %@"},
    {"ADF-MF-16219", "loginComplete ep\u00E4onnistui. Poikkeus: %@"},
    {"ADF-MF-16220", "Luokan %@ palautustyyppi\u00E4 ei voitu m\u00E4\u00E4ritt\u00E4\u00E4 menetelm\u00E4lle %@."},
    {"ADF-MF-16221", "Menetelm\u00E4n %@ palautustyyppi on virheellinen luokassa %@."},
    {"ADF-MF-16222", "Ongelma toimitettaessa tietojen muutostapahtumia ominaisuudelle %1@ k\u00E4sitellyill\u00E4 JSON-tiedoilla %2@. Odotettiin palautettua arvoa %3@, mutta se oli %4@."},
    {"ADF-MF-16223", "Argumenteissa ei ole m\u00E4\u00E4ritetty ilmoituksen tunnusta"},
    {"ADF-MF-16224", "Ei voi ajoittaa paikallista ilmoitusta, m\u00E4\u00E4ritetty p\u00E4iv\u00E4m\u00E4\u00E4r\u00E4 on virheellinen"},
    {"ADF-MF-16225", "Ei voi ajoittaa paikallista ilmoitusta, m\u00E4\u00E4ritetty toistov\u00E4li on virheellinen"},
    {"ADF-MF-16226", "Ei voi ajoittaa paikallista ilmoitusta, m\u00E4\u00E4ritetty merkki on virheellinen"},
    {"ADF-MF-16227", "Ei voi ajoittaa paikallista ilmoitusta, m\u00E4\u00E4ritetty \u00E4\u00E4ni on virheellinen"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
