// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_es extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Uso no v\u00E1lido"},
    {"ADF-MF-16004", "Esta funci\u00F3n NO se debe llamar en el thread principal."},
    {"ADF-MF-16022", "Argumento no v\u00E1lido"},
    {"ADF-MF-16023", "Se ha transferido un nombre de paquete nulo a [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "El nombre de propiedad no puede ser nula."},
    {"ADF-MF-16027", "Falta el nombre de clase."},
    {"ADF-MF-16028", "Falta el m\u00E9todo."},
    {"ADF-MF-16032", "Respuesta inesperada"},
    {"ADF-MF-16033", "La respuesta de CVM ha devuelto una respuesta nula. "},
    {"ADF-MF-16034", "La respuesta de CVM ha devuelto un FeatureContextAccessor nil."},
    {"ADF-MF-16035", "La respuesta de JS ha devuelto una respuesta nil."},
    {"ADF-MF-16036", "No se pueden enviar llamadas de JavaScript al canal '%@' que no tiene webview."},
    {"ADF-MF-16074", "Mensaje no v\u00E1lido"},
    {"ADF-MF-16075", "Tipo de mensaje desconocido especificado por el mensaje."},
    {"ADF-MF-16092", "Mensaje con formato incorrecto"},
    {"ADF-MF-16093", "No est\u00E1 permitido que el mensaje de solicitud est\u00E9 vac\u00EDo."},
    {"ADF-MF-16094", "Mensaje no soportado"},
    {"ADF-MF-16095", "Los mensajes del sistema no est\u00E1n soportados en este canal"},
    {"ADF-MF-16096", "Solicitud de sistema no v\u00E1lida %@"},
    {"ADF-MF-16097", "Los mensajes de aplicaci\u00F3n no est\u00E1n soportados en este canal"},
    {"ADF-MF-16098", "Solicitud de aplicaci\u00F3n no v\u00E1lida %@"},
    {"ADF-MF-16099", "Mensaje no tratado"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ID de referencia: %d Tipo: %d Cuerpo: %@"},
    {"ADF-MF-16101", "Se ha recibido un mensaje de respuesta no solicitado"},
    {"ADF-MF-16102", "Se ha recibido un tipo de mensaje desconocido"},
    {"ADF-MF-16103", "AdfChannel.handle - Error al manejar el mensaje de VMChannel: %@ - ERROR: %@"},
    {"ADF-MF-16113", "No se ha encontrado o no se puede leer el anexo %@"},
    {"ADF-MF-16115", "%@ no est\u00E1 definido en webview para la funci\u00F3n %@. Llamada de resultado JavaScript abortada."},
    {"ADF-MF-16116", "Se ha producido un problema al llamar a la funci\u00F3n '%@' en la funci\u00F3n %@. Valor devuelto: %@"},
    {"ADF-MF-16133", "Fallo al mostrar la funci\u00F3n"},
    {"ADF-MF-16134", "No se ha podido mostrar la funci\u00F3n. Fallo al intentar mostrar la funci\u00F3n '%@'. ERROR: %@"},
    {"ADF-MF-16142", "No se puede enviar el mensaje"},
    {"ADF-MF-16143", "No se ha podido enviar un mensaje porque los mensajes de texto no est\u00E1n disponibles en este dispositivo."},
    {"ADF-MF-16144", "No se ha podido enviar un mensaje porque no se ha podido obtener el compositor de mensajes de texto."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest: no se ha especificado 'classname'"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest: la llamada a morphClassName ha producido un ERROR: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest: fallo de morphClassName de 'classname'"},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest: no se ha especificado 'method'"},
    {"ADF-MF-16149", "No se ha podido crear la clase: %@"},
    {"ADF-MF-16150", "No se ha podido crear la clase solicitada a la que se va a llamar: %@"},
    {"ADF-MF-16151", "La instancia de la clase %@ no responde al selector '%@'."},
    {"ADF-MF-16152", "La llamada a '%@' ha provocado el error: %@"},
    {"ADF-MF-16153", "La serializaci\u00F3n del resultado de '%@' en el tipo %@ ha producido el ERROR: %@"},
    {"ADF-MF-16154", "La serializaci\u00F3n del resultado de '%@' en el tipo %@ ha generado nulo."},
    {"ADF-MF-16156", "credentialStoreKey para la conexi\u00F3n no puede ser nula."},
    {"ADF-MF-16189", "Desconexi\u00F3n"},
    {"ADF-MF-16203", "No se ha encontrado el archivo: %@"},
    {"ADF-MF-16204", "El mensaje de correo electr\u00F3nico no se ha guardado ni puesto en cola, probablemente debido a un error."},
    {"ADF-MF-16205", "Se ha producido un error al intentar guardar el mensaje de correo electr\u00F3nico en la carpeta Borradores."},
    {"ADF-MF-16206", "Se ha producido un error al intentar poner en cola o enviar el mensaje de correo electr\u00F3nico."},
    {"ADF-MF-16207", "Se ha producido un error desconocido al intentar redactar o enviar un mensaje de correo electr\u00F3nico."},
    {"ADF-MF-16208", "Se ha producido un error desconocido al intentar redactar o enviar un mensaje de texto."},
    {"ADF-MF-16209", "Archivo no encontrado"},
    {"ADF-MF-16213", "No est\u00E1 permitida la llamada a Java en otra funci\u00F3n."},
    {"ADF-MF-16214", "Violaci\u00F3n de Acceso"},
    {"ADF-MF-16215", "No se ha podido cifrar la contrase\u00F1a: %@"},
    {"ADF-MF-16216", "No se ha podido generar la contrase\u00F1a mediante hash: %@"},
    {"ADF-MF-16217", "No se ha podido descifrar la contrase\u00F1a: %@"},
    {"ADF-MF-16218", "Clave de par\u00E1metro no v\u00E1lida. ParameterKey= %@"},
    {"ADF-MF-16219", "Fallo de loginComplete con excepci\u00F3n: %@"},
    {"ADF-MF-16220", "No se ha podido determinar el tipo de retorno de clase %@ para el m\u00E9todo %@."},
    {"ADF-MF-16221", "Tipo de retorno no v\u00E1lido para el m\u00E9todo %@ en la clase %@."},
    {"ADF-MF-16222", "Se ha producido un problema al entregar los eventos de cambio de datos a la funci\u00F3n '%1@' con carga \u00FAtil JSON '%2@'.  Se esperaba el valor de devoluci\u00F3n '%3@', pero es '%4@'."},
    {"ADF-MF-16223", "No se ha especificado ning\u00FAn ID de notificaci\u00F3n en los argumentos"},
    {"ADF-MF-16224", "No se ha podido programar ninguna notificaci\u00F3n local, se ha especificado una fecha no v\u00E1lida"},
    {"ADF-MF-16225", "No se ha podido programar ninguna notificaci\u00F3n local, se ha especificado un intervalo de repetici\u00F3n no v\u00E1lido"},
    {"ADF-MF-16226", "No se ha podido programar ninguna notificaci\u00F3n local, se ha especificado una placa no v\u00E1lida"},
    {"ADF-MF-16227", "No se ha podido programar ninguna notificaci\u00F3n local, se ha especificado un sonido no v\u00E1lido"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
