// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_cs extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Neplatn\u00E9 pou\u017Eit\u00ED"},
    {"ADF-MF-16004", "Tato funkce NESM\u00CD b\u00FDt vol\u00E1na v hlavn\u00EDm vl\u00E1knu."},
    {"ADF-MF-16022", "Neplatn\u00FD argument"},
    {"ADF-MF-16023", "Metod\u011B [oraADFLogger getLogger:] byl p\u0159ed\u00E1n pr\u00E1zdn\u00FD n\u00E1zev bal\u00ED\u010Dku."},
    {"ADF-MF-16025", "N\u00E1zev vlastnosti nem\u016F\u017Ee b\u00FDt nulov\u00FD."},
    {"ADF-MF-16027", "Chyb\u00ED n\u00E1zev t\u0159\u00EDdy."},
    {"ADF-MF-16028", "Chyb\u00ED metoda."},
    {"ADF-MF-16032", "Neo\u010Dek\u00E1van\u00E1 odpov\u011B\u010F"},
    {"ADF-MF-16033", "Odpov\u011B\u010F CVM vr\u00E1tila nulovou odpov\u011B\u010F. "},
    {"ADF-MF-16034", "Odpov\u011B\u010F CVM vr\u00E1tila nulov\u00FD objekt FeatureContextAccessor."},
    {"ADF-MF-16035", "Odpov\u011B\u010F JS vr\u00E1tila nulovou odpov\u011B\u010F"},
    {"ADF-MF-16036", "Nelze odeslat vol\u00E1n\u00ED JavaScript do kan\u00E1lu '%@', kter\u00FD nem\u00E1 webov\u00E9 zobrazen\u00ED."},
    {"ADF-MF-16074", "Neplatn\u00E1 zpr\u00E1va"},
    {"ADF-MF-16075", "Ve zpr\u00E1v\u011B byl specifikov\u00E1n nezn\u00E1m\u00FD typ zpr\u00E1vy."},
    {"ADF-MF-16092", "Nespr\u00E1vn\u011B vytvo\u0159en\u00E1 zpr\u00E1va"},
    {"ADF-MF-16093", "Nen\u00ED povolena pr\u00E1zdn\u00E1 zpr\u00E1va s po\u017Eadavkem."},
    {"ADF-MF-16094", "Nepodporovan\u00E1 zpr\u00E1va"},
    {"ADF-MF-16095", "V tomto kan\u00E1lu nejsou syst\u00E9mov\u00E9 zpr\u00E1vy podporov\u00E1ny"},
    {"ADF-MF-16096", "Neplatn\u00FD syst\u00E9mov\u00FD po\u017Eadavek %@"},
    {"ADF-MF-16097", "V tomto kan\u00E1lu nejsou zpr\u00E1vy aplikace podporov\u00E1ny"},
    {"ADF-MF-16098", "Neplatn\u00FD po\u017Eadavek na aplikaci %@"},
    {"ADF-MF-16099", "Nezpracovan\u00E1 zpr\u00E1va"},
    {"ADF-MF-16100", "Nezpracovan\u00E1 zpr\u00E1va Adf - Referen\u010Dn\u00ED ID: %d Typ: %d T\u011Blo zpr\u00E1vy: %@"},
    {"ADF-MF-16101", "Byla p\u0159ijata nevy\u017E\u00E1dan\u00E1 zpr\u00E1va s odpov\u011Bd\u00ED"},
    {"ADF-MF-16102", "Byla p\u0159ijata zpr\u00E1va nezn\u00E1m\u00E9ho typu"},
    {"ADF-MF-16103", "AdfChannel.handle - Chyba p\u0159i zpracov\u00E1n\u00ED kan\u00E1lu VMChannel: %@ - ERROR: %@"},
    {"ADF-MF-16113", "P\u0159\u00EDloha %@ nebyla nalezena nebo ji nelze p\u0159e\u010D\u00EDst"},
    {"ADF-MF-16115", "%@ nen\u00ED ve webov\u00E9m zobrazen\u00ED definov\u00E1n pro funkci %@. Vol\u00E1n\u00ED v\u00FDsledku JavaScript bylo p\u0159eru\u0161eno."},
    {"ADF-MF-16116", "Do\u0161lo k probl\u00E9mu p\u0159i vol\u00E1n\u00ED funkce '%@' ve funkci %@. Vr\u00E1cena hodnota: %@"},
    {"ADF-MF-16133", "Zobrazen\u00ED funkce selhalo"},
    {"ADF-MF-16134", "Funkci nelze zobrazit. Pokus o zobrazen\u00ED funkce '%@' selhal.  CHYBA: %@"},
    {"ADF-MF-16142", "Nelze odeslat zpr\u00E1vu"},
    {"ADF-MF-16143", "Textovou zpr\u00E1vu nelze odeslat, proto\u017Ee odes\u00EDl\u00E1n\u00ED textov\u00FDch zpr\u00E1v nen\u00ED v tomto za\u0159\u00EDzen\u00ED povoleno."},
    {"ADF-MF-16144", "Nelze odeslat zpr\u00E1vu, proto\u017Ee se nepoda\u0159ilo na\u010D\u00EDst aplikaci pro sestaven\u00ED zpr\u00E1vy."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - Nebylo zad\u00E1no 'classname'"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - Vol\u00E1n\u00ED metody morphClassName zp\u016Fsobilo CHYBU: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - Metoda morphClassName t\u0159\u00EDdy 'classname' selhala."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - Nebylo zad\u00E1no 'method'"},
    {"ADF-MF-16149", "Nelze vytvo\u0159it t\u0159\u00EDdu: %@"},
    {"ADF-MF-16150", "Po\u017Eadovanou t\u0159\u00EDdu, kter\u00E1 m\u00E1 b\u00FDt vol\u00E1na, nemohla b\u00FDt vytvo\u0159ena: %@"},
    {"ADF-MF-16151", "Instance t\u0159\u00EDdy %@ neodpov\u011Bd\u011Bla na selektor '%@'."},
    {"ADF-MF-16152", "Vol\u00E1n\u00ED '%@' zp\u016Fsobilo chybu: %@"},
    {"ADF-MF-16153", "Serializace v\u00FDsledk\u016F z '%@' na typ %@ zp\u016Fsobila CHYBU: %@"},
    {"ADF-MF-16154", "Serializace v\u00FDsledk\u016F z '%@' na typ %@ generovala nulovou hodnotu."},
    {"ADF-MF-16156", "credentialStoreKey pro p\u0159ipojen\u00ED nem\u016F\u017Ee m\u00EDt nulovou hodnotu"},
    {"ADF-MF-16189", "Odhl\u00E1sit"},
    {"ADF-MF-16203", "Soubor nebyl nalezen: %@"},
    {"ADF-MF-16204", "E-mailov\u00E1 zpr\u00E1va nebyla ulo\u017Eena nebo za\u0159azena do fronty, pravd\u011Bpodobn\u011B z d\u016Fvodu chyby."},
    {"ADF-MF-16205", "P\u0159i pokusu o ulo\u017Een\u00ED e-mailov\u00E9 zpr\u00E1vy do slo\u017Eky Koncepty do\u0161lo k chyb\u011B."},
    {"ADF-MF-16206", "P\u0159i pokusu o za\u0159azen\u00ED e-mailov\u00E9 zpr\u00E1vy do fronty nebo jej\u00ED odesl\u00E1n\u00ED do\u0161lo k chyb\u011B."},
    {"ADF-MF-16207", "P\u0159i pokusu o vytvo\u0159en\u00ED nebo odesl\u00E1n\u00ED e-mailu do\u0161lo k nezn\u00E1m\u00E9 chyb\u011B."},
    {"ADF-MF-16208", "P\u0159i pokusu o vytvo\u0159en\u00ED nebo odesl\u00E1n\u00ED textov\u00E9 zpr\u00E1vy do\u0161lo k nezn\u00E1m\u00E9 chyb\u011B."},
    {"ADF-MF-16209", "Soubor nebyl nalezen"},
    {"ADF-MF-16213", "Vol\u00E1n\u00ED vyvol\u00E1n\u00ED Java na jin\u00E9 funkci nen\u00ED dovoleno."},
    {"ADF-MF-16214", "Poru\u0161en\u00ED p\u0159\u00EDstupu"},
    {"ADF-MF-16215", "Nelze za\u0161ifrovat heslo: %@"},
    {"ADF-MF-16216", "Nelze generovat heslo pomoc\u00ED operace hashing: %@"},
    {"ADF-MF-16217", "Nelze de\u0161ifrovat heslo: %@"},
    {"ADF-MF-16218", "Neplatn\u00FD kl\u00ED\u010D parametru. ParameterKey= %@"},
    {"ADF-MF-16219", "Metoda loginComplete selhala s v\u00FDjimkou: %@"},
    {"ADF-MF-16220", "Nelze ur\u010Dit n\u00E1vratov\u00FD typ t\u0159\u00EDdy %@ pro metodu %@."},
    {"ADF-MF-16221", "Neplatn\u00FD n\u00E1vratov\u00FD typ pro metodu %@ ve t\u0159\u00EDd\u011B %@."},
    {"ADF-MF-16222", "Do\u0161lo k probl\u00E9mu p\u0159i poskytov\u00E1n\u00ED ud\u00E1lost\u00ED zm\u011Bny dat pro funkci '%1@' s datovou \u010D\u00E1st\u00ED JSON '%2@'.  O\u010Dek\u00E1v\u00E1na vr\u00E1cen\u00E1 hodnota '%3@', ale ve skute\u010Dnost byla '%4@'."},
    {"ADF-MF-16223", "V argumentech nen\u00ED zad\u00E1no ID upozorn\u011Bn\u00ED"},
    {"ADF-MF-16224", "Nelze pl\u00E1novat m\u00EDstn\u00ED upozorn\u011Bn\u00ED, zad\u00E1no neplatn\u00E9 datum"},
    {"ADF-MF-16225", "Nelze pl\u00E1novat m\u00EDstn\u00ED upozorn\u011Bn\u00ED, zad\u00E1n neplatn\u00FD interval opakov\u00E1n\u00ED"},
    {"ADF-MF-16226", "Nelze pl\u00E1novat m\u00EDstn\u00ED upozorn\u011Bn\u00ED, zad\u00E1no neplatn\u00E9 ozna\u010Den\u00ED"},
    {"ADF-MF-16227", "Nelze pl\u00E1novat m\u00EDstn\u00ED upozorn\u011Bn\u00ED, zad\u00E1n neplatn\u00FD zvuk"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
