// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_ro extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Utilizare nevalid\u0103"},
    {"ADF-MF-16004", "Aceast\u0103 func\u0163ie NU trebuie apelat\u0103 \u00EEn firul principal."},
    {"ADF-MF-16022", "Argument nevalid"},
    {"ADF-MF-16023", "A fost transmis un pachet cu un nume nul c\u0103tre [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "Numele propriet\u0103\u0163ii nu poate fi nul."},
    {"ADF-MF-16027", "Lipse\u015Fte numele clasei."},
    {"ADF-MF-16028", "Lipse\u015Fte metoda."},
    {"ADF-MF-16032", "R\u0103spuns nea\u015Fteptat"},
    {"ADF-MF-16033", "R\u0103spunsul CVM a returnat un r\u0103spuns nul."},
    {"ADF-MF-16034", "R\u0103spunsul CVM a returnat un FeatureContextAccessor nul."},
    {"ADF-MF-16035", "R\u0103spunsul JS returnat este nul."},
    {"ADF-MF-16036", "Nu se pot trimite apeluri JavaScript c\u0103tre canalul '%@', care nu are o vizualizare web."},
    {"ADF-MF-16074", "Mesaj nevalid"},
    {"ADF-MF-16075", " Tipul de mesajul specificat este necunoscut."},
    {"ADF-MF-16092", "Mesaj formatat gre\u015Fit"},
    {"ADF-MF-16093", "Nu este permis un mesaj de cerere gol."},
    {"ADF-MF-16094", "Mesaj neacceptat"},
    {"ADF-MF-16095", "Mesajele de sistem nu sunt acceptate pe acest canal"},
    {"ADF-MF-16096", "Cerere de sistem nevalid\u0103 %@"},
    {"ADF-MF-16097", "Mesajele de aplica\u0163ie nu sunt acceptate pe acest canal"},
    {"ADF-MF-16098", "Cerere de aplica\u0163ie nevalid\u0103 %@"},
    {"ADF-MF-16099", "Mesaj netratat"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d Tip: %d Corp: %@"},
    {"ADF-MF-16101", "S-a primit un mesaj de r\u0103spuns nesolicitat"},
    {"ADF-MF-16102", "S-a primit un tip de mesaj necunoscut"},
    {"ADF-MF-16103", "AdfChannel.handle - Eroare la tratarea mesajului VMChannel: %@ - EROARE: %@"},
    {"ADF-MF-16113", "Ata\u015Famentul %@ nu a putut fi g\u0103sit sau citit"},
    {"ADF-MF-16115", "%@ nu este definit \u00EEn vizualizarea web pt. caracteristica %@. Apelarea pt. rezultatul JavaScript a fost abandonat\u0103."},
    {"ADF-MF-16116", "A survenit o problem\u0103 la apelarea func\u0163iei '%@' din caracteristica %@. Valoare returnat\u0103: %@"},
    {"ADF-MF-16133", "Afi\u015Farea caracteristicii a e\u015Fuat"},
    {"ADF-MF-16134", "Caracteristica nu a putut fi afi\u015Fat\u0103. \u00CEncercarea de afi\u015Fare a caracteristicii '%@' a e\u015Fuat. EROARE: %@"},
    {"ADF-MF-16142", "Mesajul nu a putut fi trimis"},
    {"ADF-MF-16143", "Mesajul nu s-a putut trimite, deoarece pe acest dispozitiv nu sunt disponibile mesajele de text."},
    {"ADF-MF-16144", "Mesajul nu a putut fi trimis, deoarece nu s-a putut deschide redactorul de mesaje text."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - Nu s-a specificat 'classname'"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - A survenit o eroare la apelarea morphClassName. Eroarea este: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - 'classname' morphClassName a e\u015Fuat."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - Nu s-a specificat 'method'"},
    {"ADF-MF-16149", "Nu s-a putut crea clasa: %@"},
    {"ADF-MF-16150", "Clasa solicitat\u0103 pt. a fi invocat\u0103 nu a putut fi creat\u0103: %@"},
    {"ADF-MF-16151", "Instan\u0163a clasei %@ nu r\u0103spunde la selectorul '%@'."},
    {"ADF-MF-16152", "Invocarea '%@' a dus la o eroare: %@"},
    {"ADF-MF-16153", "Serializarea rezultatului din tipul '%@' \u00EEn %@ a dus la o eroare: %@"},
    {"ADF-MF-16154", "Serializarea rezultatului din tipul '%@' \u00EEn %@ a generat valoarea zero."},
    {"ADF-MF-16156", "credentialStoreKey pt. conexiune nu poate fi zero"},
    {"ADF-MF-16189", "Deconectare"},
    {"ADF-MF-16203", "Fi\u015Fierul nu a fost g\u0103sit: %@"},
    {"ADF-MF-16204", "Mesajul de e-mail nu a fost salvat \u015Fi nici plasat \u00EEn coad\u0103, probabil din cauza unei erori."},
    {"ADF-MF-16205", "A survenit o eroare la \u00EEncercarea de a salva mesajul de e-mail \u00EEn folderul cu ciorne."},
    {"ADF-MF-16206", "A survenit o eroare la \u00EEncercarea de a plasa \u00EEn coad\u0103 sau de a trimite mesajul de e-mail."},
    {"ADF-MF-16207", "A survenit o eroare necunoscut\u0103 la \u00EEncercarea de a redacta sau de a trimite un e-mail"},
    {"ADF-MF-16208", "A survenit o eroare necunoscut\u0103 la \u00EEncercarea de a redacta sau de a trimite un mesaj text"},
    {"ADF-MF-16209", "Fi\u015Fierul nu a fost g\u0103sit"},
    {"ADF-MF-16213", "Apelarea Invocare Java pt. alt\u0103 caracteristic\u0103 nu este permis\u0103."},
    {"ADF-MF-16214", "\u00CEnc\u0103lcare acces"},
    {"ADF-MF-16215", "Nu s-a putut cripta parola: %@"},
    {"ADF-MF-16216", "Nu s-a putut genera parola prin hashing: %@"},
    {"ADF-MF-16217", "Nu s-a putut decripta parola: %@"},
    {"ADF-MF-16218", "Cheie nevalid\u0103 pt. parametru. ParameterKey = %@"},
    {"ADF-MF-16219", "loginComplete a e\u015Fuat cu excep\u0163ia: %@"},
    {"ADF-MF-16220", "Nu s-a putut stabili tipul de returnare al clasei %@ pt. metoda %@."},
    {"ADF-MF-16221", "Tip de returnare nevalid pt. metoda %@ din clasa %@."},
    {"ADF-MF-16222", "A survenit o problem\u0103 la livrarea evenimentelor de modificare a datelor c\u0103tre caracteristica '%1@' cu payloadul JSON '%2@'. Se a\u015Ftepta valoarea returnat\u0103 '%3@', dar aceasta a fost efectiv '%4@'."},
    {"ADF-MF-16223", "Nu a fost specificat niciun ID de \u00EEn\u015Ftiin\u0163are \u00EEn argumente"},
    {"ADF-MF-16224", "Nu s-a putut programa o \u00EEn\u015Ftiin\u0163are local\u0103; a fost specificat\u0103 o dat\u0103 nevalid\u0103"},
    {"ADF-MF-16225", "Nu s-a putut programa o \u00EEn\u015Ftiin\u0163are local\u0103; a fost specificat un interval de repetare nevalid"},
    {"ADF-MF-16226", "Nu s-a putut programa o \u00EEn\u015Ftiin\u0163are local\u0103; a fost specificat un ecuson nevalid"},
    {"ADF-MF-16227", "Nu s-a putut programa o \u00EEn\u015Ftiin\u0163are local\u0103; a fost specificat un sunet nevalid"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
