// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_tr extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Ge\u00E7ersiz Kullan\u0131m"},
    {"ADF-MF-16004", "Bu fonksiyon ana thread \u00FCzerinde \u00C7A\u011ERILMAMALIDIR."},
    {"ADF-MF-16022", "Ge\u00E7ersiz Ba\u011F\u0131ms\u0131z De\u011Fi\u015Fken"},
    {"ADF-MF-16023", "[oraADFLogger getLogger:] \u00F6\u011Fesine bo\u015F paket ad\u0131 aktar\u0131ld\u0131."},
    {"ADF-MF-16025", "Nitelik ad\u0131 bo\u015F olamaz."},
    {"ADF-MF-16027", "Eksik s\u0131n\u0131f ad\u0131."},
    {"ADF-MF-16028", "Eksik y\u00F6ntem."},
    {"ADF-MF-16032", "Beklenmeyen Yan\u0131t"},
    {"ADF-MF-16033", "CVM Yan\u0131t\u0131 bo\u015F yan\u0131t d\u00F6nd\u00FCrd\u00FC. "},
    {"ADF-MF-16034", "CVM Yan\u0131t\u0131 bo\u015F FeatureContextAccessor d\u00F6nd\u00FCrd\u00FC."},
    {"ADF-MF-16035", "JS Yan\u0131t\u0131 bo\u015F yan\u0131t d\u00F6nd\u00FCrd\u00FC."},
    {"ADF-MF-16036", "JavaScript \u00E7a\u011Fr\u0131lar\u0131, web g\u00F6r\u00FCn\u00FCm\u00FCne sahip olmayan '%@' kanal\u0131na g\u00F6nderilemiyor."},
    {"ADF-MF-16074", "Ge\u00E7ersiz Mesaj"},
    {"ADF-MF-16075", "Mesaj taraf\u0131ndan Bilinmeyen Mesaj T\u00FCr\u00FC belirtildi."},
    {"ADF-MF-16092", "Hatal\u0131 Mesaj Format\u0131"},
    {"ADF-MF-16093", "Bo\u015F istek mesaj\u0131na izin verilmez."},
    {"ADF-MF-16094", "Desteklenmeyen Mesaj"},
    {"ADF-MF-16095", "Sistem mesajlar\u0131 bu kanalda desteklenmez"},
    {"ADF-MF-16096", "Ge\u00E7ersiz sitem iste\u011Fi %@"},
    {"ADF-MF-16097", "Uygulama mesajlar\u0131 bu kanalda desteklenmez"},
    {"ADF-MF-16098", "Ge\u00E7ersiz uygulama iste\u011Fi %@"},
    {"ADF-MF-16099", "\u0130\u015Flenmeyen Mesaj"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ReferenceId: %d T\u00FCr: %d G\u00F6vde: %@"},
    {"ADF-MF-16101", "\u0130stenmeyen yan\u0131t mesaj\u0131 al\u0131nd\u0131"},
    {"ADF-MF-16102", "Bilinmeyen mesaj t\u00FCr\u00FC al\u0131nd\u0131"},
    {"ADF-MF-16103", "AdfChannel.handle - VMChannel mesaj\u0131 i\u015Flenirken hata olu\u015Ftu: %@ - HATA: %@"},
    {"ADF-MF-16113", "%@ eki bulunamad\u0131 veya okunamad\u0131"},
    {"ADF-MF-16115", "%@ \u00F6zelli\u011Fi i\u00E7in web g\u00F6r\u00FCn\u00FCm\u00FCnde %@ tan\u0131mlanmad\u0131. JavaScript sonu\u00E7 \u00E7a\u011Fr\u0131s\u0131 durduruldu."},
    {"ADF-MF-16116", "%@ \u00F6zelli\u011Finde '%@' fonksiyonu \u00E7a\u011Fr\u0131l\u0131rken sorun olu\u015Ftu. D\u00F6nd\u00FCr\u00FClen de\u011Fer: %@"},
    {"ADF-MF-16133", "\u00D6zellik G\u00F6sterilemedi"},
    {"ADF-MF-16134", "\u00D6zellik g\u00F6sterilemedi. '%@' \u00F6zelli\u011Fini g\u00F6sterme denemesi ba\u015Far\u0131s\u0131z oldu. HATA: %@"},
    {"ADF-MF-16142", "Mesaj G\u00F6nderilemiyor"},
    {"ADF-MF-16143", "Metin tabanl\u0131 haberle\u015Fme bu ayg\u0131tta kullan\u0131lmad\u0131\u011F\u0131 i\u00E7in mesaj g\u00F6nderilemiyor."},
    {"ADF-MF-16144", "Metin mesaj\u0131 olu\u015Fturucusu al\u0131namad\u0131\u011F\u0131ndan mesaj g\u00F6nderilemiyor."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - 's\u0131n\u0131f ad\u0131' belirtilmedi"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - morphClassName \u00E7a\u011Fr\u0131s\u0131 HATAYA neden oldu: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - 's\u0131n\u0131f ad\u0131' morphClassName ba\u015Far\u0131s\u0131z oldu."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - 'y\u00F6ntem' belirtilmedi"},
    {"ADF-MF-16149", "S\u0131n\u0131f yarat\u0131lamad\u0131: %@"},
    {"ADF-MF-16150", "\u00C7a\u011Fr\u0131lacak istenen s\u0131n\u0131f yarat\u0131lamad\u0131: %@"},
    {"ADF-MF-16151", "%@ s\u0131n\u0131f\u0131n\u0131n an\u0131 , '%@' se\u00E7iciye yan\u0131t vermiyor."},
    {"ADF-MF-16152", "'%@' \u00E7a\u011F\u0131rma i\u015Flemi hataya neden oldu: %@"},
    {"ADF-MF-16153", "%@ t\u00FCr\u00FC \u00FCzerinde '%@' kaynakl\u0131 \u00E7\u00F6z\u00FCm\u00FCn serile\u015Ftirilmesi HATAYA neden oldu: %@"},
    {"ADF-MF-16154", "%@ t\u00FCr\u00FC \u00FCzerinde '%@' kaynakl\u0131 \u00E7\u00F6z\u00FCm\u00FCn serile\u015Ftirilmesi bo\u015F de\u011Fer olu\u015Fturdu."},
    {"ADF-MF-16156", "Ba\u011Flant\u0131 i\u00E7in credentialStoreKey bo\u015F olamaz"},
    {"ADF-MF-16189", "Oturumu Kapat"},
    {"ADF-MF-16203", "Dosya bulunamad\u0131: %@"},
    {"ADF-MF-16204", "B\u00FCy\u00FCk olas\u0131l\u0131kla bir hata nedeniyle e-posta mesaj\u0131 kaydedilmedi veya kuyru\u011Fa al\u0131nmad\u0131."},
    {"ADF-MF-16205", "E-posta mesaj\u0131 Taslaklar klas\u00F6r\u00FCne kaydedilmeye \u00E7al\u0131\u015F\u0131l\u0131rken hata olu\u015Ftu."},
    {"ADF-MF-16206", "E-posta mesaj\u0131n\u0131 kuyru\u011Fa alma ve g\u00F6nderme giri\u015Fiminde hata olu\u015Ftu."},
    {"ADF-MF-16207", "E-posta olu\u015Fturma veya g\u00F6nderme giri\u015Fiminde bilinmeyen hata olu\u015Ftu."},
    {"ADF-MF-16208", "Metin mesaj\u0131 olu\u015Fturma veya g\u00F6nderme giri\u015Fiminde bilinmeyen hata olu\u015Ftu."},
    {"ADF-MF-16209", "Dosya bulunamad\u0131"},
    {"ADF-MF-16213", "Ba\u015Fka bir \u00F6zellikte Java \u00C7a\u011F\u0131r i\u015Flemine izin verilmiyor."},
    {"ADF-MF-16214", "Eri\u015Fim ihlali"},
    {"ADF-MF-16215", "Parola \u015Fifresi yarat\u0131lam\u0131yor: %@"},
    {"ADF-MF-16216", "Hash i\u015Flemi yoluyla parola olu\u015Fturulam\u0131yor: %@"},
    {"ADF-MF-16217", "Parola \u015Fifresi \u00E7\u00F6z\u00FClemiyor: %@"},
    {"ADF-MF-16218", "Ge\u00E7ersiz parametre anahtar\u0131. Parametre Anahtar\u0131= %@"},
    {"ADF-MF-16219", "loginComplete, %@ istisnas\u0131yla ba\u015Far\u0131s\u0131z oldu"},
    {"ADF-MF-16220", "%@ y\u00F6ntemi i\u00E7in %@ s\u0131n\u0131f\u0131n\u0131n d\u00F6n\u00FC\u015F t\u00FCr\u00FC belirlenemedi."},
    {"ADF-MF-16221", "%@ s\u0131n\u0131f\u0131nda %@ y\u00F6ntemi i\u00E7in ge\u00E7ersiz d\u00F6n\u00FC\u015F t\u00FCr\u00FC."},
    {"ADF-MF-16222", "Veri de\u011Fi\u015Fikli\u011Fi etkinlikleri '%1@' \u00F6zelli\u011Fine '%2@' JSON i\u015Flenmi\u015F bilgisiyle teslim edilirken sorun olu\u015Ftu. Beklenen d\u00F6n\u00FC\u015F de\u011Feri '%3@', ancak '%4@' al\u0131nd\u0131."},
    {"ADF-MF-16223", "Ba\u011F\u0131ms\u0131z de\u011Fi\u015Fkenlerde belirtilen bir bildirim no yok"},
    {"ADF-MF-16224", "Bir yerel bildirim \u00E7izelgelenemiyor, ge\u00E7ersiz tarih belirtildi"},
    {"ADF-MF-16225", "Bir yerel bildirim \u00E7izelgelenemiyor, ge\u00E7ersiz yineleme aral\u0131\u011F\u0131 belirtildi"},
    {"ADF-MF-16226", "Bir yerel bildirim \u00E7izelgelenemiyor, ge\u00E7ersiz rozet belirtildi"},
    {"ADF-MF-16227", "Bir yerel bildirim \u00E7izelgelenemiyor, ge\u00E7ersiz ses belirtildi"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
