// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_it extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Uso non valido"},
    {"ADF-MF-16004", "Questa funzione NON deve essere chiamata sul thread principale."},
    {"ADF-MF-16022", "Argomento non valido."},
    {"ADF-MF-16023", "Nome package nullo passato a [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "Il nome della propriet\u00E0 non pu\u00F2 essere nullo."},
    {"ADF-MF-16027", "Nome classe mancante."},
    {"ADF-MF-16028", "Metodo mancante."},
    {"ADF-MF-16032", "Risposta imprevista"},
    {"ADF-MF-16033", "La risposta CVM ha restituito una risposta nulla. "},
    {"ADF-MF-16034", "La risposta CVM ha restituito un FeatureContextAccessor nullo."},
    {"ADF-MF-16035", "La risposta JS ha restituito una risposta nulla."},
    {"ADF-MF-16036", "Impossibile inviare le chiamate JavaScript al canale '%@' che non ha una vista Web."},
    {"ADF-MF-16074", "Messaggio non valido"},
    {"ADF-MF-16075", "Tipo di messaggio sconosciuto specificato dal messaggio."},
    {"ADF-MF-16092", "Messaggio con formato non valido"},
    {"ADF-MF-16093", "Non \u00E8 consentito un messaggio di richiesta vuoto."},
    {"ADF-MF-16094", "Messaggio non supportato"},
    {"ADF-MF-16095", "Messaggi di sistema non supportati su questo canale"},
    {"ADF-MF-16096", "Richiesta di sistema non valida %@"},
    {"ADF-MF-16097", "Messaggi dell'applicazione non supportati su questo canale"},
    {"ADF-MF-16098", "Richiesta dell'applicazione non valida %@"},
    {"ADF-MF-16099", "Messaggio non gestito"},
    {"ADF-MF-16100", "UnhandledAdfMessage - ID riferimento: %d Tipo: %d Corpo: %@"},
    {"ADF-MF-16101", "\u00C8 stato ricevuto un messaggio di risposta non richiesto"},
    {"ADF-MF-16102", "\u00C8 stato ricevuto un tipo di messaggio sconosciuto"},
    {"ADF-MF-16103", "AdfChannel.handle - Errore durante la gestione del messaggio VMChannel: %@ - ERRORE: %@"},
    {"ADF-MF-16113", "Impossibile trovare o leggere l'allegato %@"},
    {"ADF-MF-16115", "%@ non definito in WebView per la funzione %@. Chiamata JavaScript risultante interrotta."},
    {"ADF-MF-16116", "Problema durante la chiamata della funzione '%@' in%@. Restituito il valore: %@"},
    {"ADF-MF-16133", "Visualizzazione della funzione non riuscita"},
    {"ADF-MF-16134", "Impossibile visualizzare la funzione. Tentativo di visualizzare la funzione '%@' non riuscito. ERRORE: %@"},
    {"ADF-MF-16142", "Impossibile inviare il messaggio"},
    {"ADF-MF-16143", "Impossibile inviare il messaggio. Messaggistica di testo non disponibile su questo dispositivo."},
    {"ADF-MF-16144", "Impossibile inviare il messaggio. Impossibile ottenere il composer di messaggi di testo."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - 'nome classe' non specificato"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - la chiamata a morphClassName ha provocato un ERRORE: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - 'nome classe' morphClassName non riuscito."},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest -'metodo' non specificato"},
    {"ADF-MF-16149", "Impossibile creare una classe: %@"},
    {"ADF-MF-16150", "Impossibile creare la classe richiesta da richiamare: %@"},
    {"ADF-MF-16151", "L'istanza della classe %@ non risponde al selettore '%@'."},
    {"ADF-MF-16152", "Il richiamo di '%@' ha provocato un errore: %@"},
    {"ADF-MF-16153", "La serializzazione del risultato da '%@' sul tipo %@ ha provocato un ERRORE: %@"},
    {"ADF-MF-16154", "La serializzazione del risultato da '%@' sul tipo %@ ha generato un valore nullo."},
    {"ADF-MF-16156", "credentialStoreKey per la connessione non pu\u00F2 essere nulla"},
    {"ADF-MF-16189", "Logout"},
    {"ADF-MF-16203", "File non trovato: %@"},
    {"ADF-MF-16204", "Messaggio di posta elettronica non salvato o non inserito nella coda a causa di un probabile errore."},
    {"ADF-MF-16205", "Si \u00E8 verificato un errore durante il tentativo di salvataggio del messaggio di posta elettronica nella cartella Bozze."},
    {"ADF-MF-16206", "Si \u00E8 verificato un errore durante il tentativo di inserire nella coda o inviare il messaggio di posta elettronica."},
    {"ADF-MF-16207", "Si \u00E8 verificato un errore sconosciuto durante il tentativo di comporre o inviare un messaggio di posta elettronica."},
    {"ADF-MF-16208", "Si \u00E8 verificato un errore sconosciuto durante il tentativo di comporre o inviare un messaggio di testo."},
    {"ADF-MF-16209", "File non trovato."},
    {"ADF-MF-16213", "La chiamata per richiamare Java su un'altra funzione non \u00E8 consentita."},
    {"ADF-MF-16214", "Violazione di accesso"},
    {"ADF-MF-16215", "Impossibile cifrare la password: %@"},
    {"ADF-MF-16216", "Impossibile generare la password tramite hashing: %@"},
    {"ADF-MF-16217", "Impossibile decifrare la password: %@"},
    {"ADF-MF-16218", "Chiave di parametro non valida. ParameterKey= %@"},
    {"ADF-MF-16219", "loginComplete non riuscito con errore: %@"},
    {"ADF-MF-16220", "Impossibile determinare il tipo restituito di classe %@ per il metodo %@."},
    {"ADF-MF-16221", "Tipo restituito non valido per il metodo %@ nella classe %@."},
    {"ADF-MF-16222", "Problema durante la consegna degli eventi di modifica dati per la funzione '%1@' con il payload JSON '%2@'. Previsto valore di restituzione  '%3@', ma rilevato '%4@'."},
    {"ADF-MF-16223", "Nessun ID di notifica specificato negli argomenti"},
    {"ADF-MF-16224", "Impossibile pianificare una notifica locale; specificata data non valida."},
    {"ADF-MF-16225", "Impossibile pianificare una notifica locale; specificato intervallo di ripetizione non valido."},
    {"ADF-MF-16226", "Impossibile pianificare una notifica locale; specificato badge non valido."},
    {"ADF-MF-16227", "Impossibile pianificare una notifica locale; specificato suono non valido."},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
