// Do not edit this file!
// This file has been automatically generated.
// Edit iOSErrorBundle.xmr and run the XMRMakeBundle tool instead.
// 
package oracle.adfmf.resource;

import java.util.ListResourceBundle;

public class iOSErrorBundle_sv extends ListResourceBundle {
  public Object[][] getContents() {
    return contents;
  }

  static final Object[][] contents = {
    {"oracle.core.ojdl.logging.MessageIdKeyResourceBundle", ""},
    {"ADF-MF-16000", "ERROR: %@"},
    {"ADF-MF-16002", "Ogiltig anv\u00E4ndning"},
    {"ADF-MF-16004", "Den h\u00E4r funktionen f\u00E5r INTE anropas i huvudtr\u00E5den."},
    {"ADF-MF-16022", "Ogiltigt argument"},
    {"ADF-MF-16023", "Ett noll-paketnamn skickades till [oraADFLogger getLogger:]."},
    {"ADF-MF-16025", "Egenskapsnamnet f\u00E5r inte vara noll"},
    {"ADF-MF-16027", "Klassnamn saknas."},
    {"ADF-MF-16028", "Metod saknas."},
    {"ADF-MF-16032", "Ov\u00E4ntat svar"},
    {"ADF-MF-16033", "CVM-svar returnerade ett noll-svar. "},
    {"ADF-MF-16034", "CVM-svar returnerade en noll-FeatureContextAccessor."},
    {"ADF-MF-16035", "JS-svar returnerade ett noll-svar."},
    {"ADF-MF-16036", "Kan inte skicka JavaScript-anrop till kanalen '%@' som inte har n\u00E5gon webbvy."},
    {"ADF-MF-16074", "Ogiltigt meddelande"},
    {"ADF-MF-16075", "Ok\u00E4nd meddelandetyp angavs av meddelande"},
    {"ADF-MF-16092", "Felaktigt utformat meddelande"},
    {"ADF-MF-16093", "Tomt meddelande om beg\u00E4ran \u00E4r inte till\u00E5tet."},
    {"ADF-MF-16094", "Meddelandet st\u00F6ds inte"},
    {"ADF-MF-16095", "Systemmeddelanden st\u00F6ds inte i den h\u00E4r kanalen"},
    {"ADF-MF-16096", "Ogiltig systembeg\u00E4ran %@"},
    {"ADF-MF-16097", "Applikationsmeddelanden st\u00F6ds inte i den h\u00E4r kanalen"},
    {"ADF-MF-16098", "Ogiltig applikationsbeg\u00E4ran %@"},
    {"ADF-MF-16099", "Meddelandet hanteras inte"},
    {"ADF-MF-16100", "Adf-meddelandet hanteras inte - Referens-id: %d Typ: %d Text: %@"},
    {"ADF-MF-16101", "Tog emot ett o\u00F6nskat svarsmeddelande"},
    {"ADF-MF-16102", "Tog emot en ok\u00E4nd meddelandetyp"},
    {"ADF-MF-16103", "AdfChannel.handle - Felhantering av VMChannel.meddelandet: %@ - FEL: %@"},
    {"ADF-MF-16113", "Bilaga %@ hittades inte eller kunde inte l\u00E4sas"},
    {"ADF-MF-16115", "%@ \u00E4r inte definierat i webbvyn f\u00F6r funktionen %@. Anropet f\u00F6r JavaScript-resultat avbr\u00F6ts."},
    {"ADF-MF-16116", "Problem vid anrop till funktionen '%@' i funktionen %@. Returnerat v\u00E4rde: %@"},
    {"ADF-MF-16133", "Kunde inte visa funktionen"},
    {"ADF-MF-16134", "Kunde inte visa funktionen. F\u00F6rs\u00F6k att visa funktionen '%@' utf\u00F6rdes inte. FEL: %@"},
    {"ADF-MF-16142", "Kan inte skicka meddelande"},
    {"ADF-MF-16143", "Kan inte skicka meddelanden eftersom det inte finns n\u00E5gon sms-tj\u00E4nst p\u00E5 den h\u00E4r enheten."},
    {"ADF-MF-16144", "Kan inte skicka meddelandet eftersom sammanst\u00E4llningen f\u00F6r textmeddelanden inte g\u00E5r att h\u00E4mta."},
    {"ADF-MF-16145", "AdfGenericInvokeHandler.processRequest - 'klassnamnet' angavs inte"},
    {"ADF-MF-16146", "adfGenericInvokeHandler.processRequest - morphClassName-anropet orsakade ett FEL: %@"},
    {"ADF-MF-16147", "AdfGenericInvokeHandler.processRequest - 'klassnamnet' morphClassName underk\u00E4ndes,"},
    {"ADF-MF-16148", "AdfGenericInvokeHandler.processRequest - 'metoden' angavs inte"},
    {"ADF-MF-16149", "Kunde inte skapa klassen: %@"},
    {"ADF-MF-16150", "Beg\u00E4rd klass som skulle anropas kunde inte skapas: %@"},
    {"ADF-MF-16151", "Instansen i klassen %@ svarar inte p\u00E5 v\u00E4ljaren '%@'."},
    {"ADF-MF-16152", "Anrop av '%@' orsakade felet: %@"},
    {"ADF-MF-16153", "Serialisering av resultat fr\u00E5n '%@' f\u00F6r typen %@ orsakade felet: %@"},
    {"ADF-MF-16154", "Serialisering av resultat fr\u00E5n '%@' f\u00F6r typen %@ genererade noll."},
    {"ADF-MF-16156", "credentialStoreKey f\u00F6r anslutningen f\u00E5r inte vara noll"},
    {"ADF-MF-16189", "Utloggning"},
    {"ADF-MF-16203", "Filen hittades inte: %@"},
    {"ADF-MF-16204", "E-postmeddelandet sparades eller k\u00F6ades inte, troligen p\u00E5 grund av ett fel."},
    {"ADF-MF-16205", "Ett fel intr\u00E4ffade vid f\u00F6rs\u00F6k att spara e-postmeddelandet i mappen Utkast."},
    {"ADF-MF-16206", "Ett fel intr\u00E4ffade vid f\u00F6rs\u00F6k att k\u00F6a eller skicka e-postmeddelandet."},
    {"ADF-MF-16207", "Ett ok\u00E4nt fel intr\u00E4ffade vid f\u00F6rs\u00F6k att skapa eller skicka ett e-postmeddelande"},
    {"ADF-MF-16208", "Ett ok\u00E4nt fel intr\u00E4ffade vid f\u00F6rs\u00F6k att skapa eller skicka ett textmeddelande"},
    {"ADF-MF-16209", "Filen hittades inte"},
    {"ADF-MF-16213", "Anrop av Anropa Java f\u00F6r en annan funktion till\u00E5ts inte."},
    {"ADF-MF-16214", "\u00C5tkomst\u00F6vertr\u00E4delse"},
    {"ADF-MF-16215", "Kan inte kryptera l\u00F6senordet: %@"},
    {"ADF-MF-16216", "Kan inte generera l\u00F6senord via hashning: %@"},
    {"ADF-MF-16217", "Kan inte dekryptera l\u00F6senordet: %@"},
    {"ADF-MF-16218", "Ogiltig parameternyckel. ParameterKey= %@"},
    {"ADF-MF-16219", "loginComplete utf\u00F6rdes inte med undantag: %@"},
    {"ADF-MF-16220", "Kunde inte fastst\u00E4lla returtyp f\u00F6r klassen %@ f\u00F6r metoden %@."},
    {"ADF-MF-16221", "Ogiltig returtyp f\u00F6r metoden %@ i klassen %@."},
    {"ADF-MF-16222", "Problem med leverans av data\u00E4ndringsh\u00E4ndelser till funktionen '%1@' med JSON-nyttolasten'%2@'. Returnerat v\u00E4rde f\u00F6rv\u00E4ntades vara '%3@' men var '%4@'."},
    {"ADF-MF-16223", "Inget meddelande-id har angetts i argumenten"},
    {"ADF-MF-16224", "Kan inte schemal\u00E4gga ett lokalt meddelande, ogiltigt datum har angetts"},
    {"ADF-MF-16225", "Kan inte schemal\u00E4gga ett lokalt meddelande, ogiltigt upprepningsintervall har angetts"},
    {"ADF-MF-16226", "Kan inte schemal\u00E4gga ett lokalt meddelande, ogiltigt emblem har angetts"},
    {"ADF-MF-16227", "Kan inte schemal\u00E4gga ett lokalt meddelande, ogiltigt ljud har angetts"},
  };

  public static final String PHRASE_KEY_ERROR = "ADF-MF-16000";
  public static final String PHRASE_KEY_INVALID_USE_TITLE = "ADF-MF-16002";
  public static final String PHRASE_KEY_REQUIRES_NON_MAIN_THREAD = "ADF-MF-16004";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_TITLE = "ADF-MF-16022";
  public static final String PHRASE_KEY_REQUIRES_NIL_PACKAGE_NAME = "ADF-MF-16023";
  public static final String PHRASE_KEY_NAME_PROPERTY_CANNOT_BE_NIL = "ADF-MF-16025";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_CLASSNAME = "ADF-MF-16027";
  public static final String PHRASE_KEY_INVALID_ARGUMENT_MISSING_METHOD = "ADF-MF-16028";
  public static final String PHRASE_KEY_UNEXPECTED_RESPONSE_TITLE = "ADF-MF-16032";
  public static final String PHRASE_KEY_CVM_NIL_RESPONSE_TITLE = "ADF-MF-16033";
  public static final String PHRASE_KEY_CVM_NIL_FEATURECONTEXTACCESSOR = "ADF-MF-16034";
  public static final String PHRASE_KEY_CVM_NIL_JS_RESPONSE_NIL = "ADF-MF-16035";
  public static final String PHRASE_KEY_CVM_NO_JS_TO_CONTROL_CHANNEL = "ADF-MF-16036";
  public static final String PHRASE_KEY_INVALID_MSG_TITLE = "ADF-MF-16074";
  public static final String PHRASE_KEY_INVALID_MSG_TYPE = "ADF-MF-16075";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_TITLE = "ADF-MF-16092";
  public static final String PHRASE_KEY_ADFCHANNEL_MALFORMED_MESSAGE_EMP_NOT_ALLOWED = "ADF-MF-16093";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_TITLE = "ADF-MF-16094";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_SYS_MSG_ON_CHNL = "ADF-MF-16095";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_SYS_REQ = "ADF-MF-16096";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSUPPORTED_MESSAGE_APP_MSG_ON_CHNL = "ADF-MF-16097";
  public static final String PHRASE_KEY_ADFCHANNEL_INVLD_APP_REQ = "ADF-MF-16098";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_TITLE = "ADF-MF-16099";
  public static final String PHRASE_KEY_ADFCHANNEL_UNHANDLED_MESSAGE_INFO = "ADF-MF-16100";
  public static final String PHRASE_KEY_ADFCHANNEL_UNSOLICITATED_RESPONSE = "ADF-MF-16101";
  public static final String PHRASE_KEY_ADFCHANNEL_UNKNWN_MSG_TYP = "ADF-MF-16102";
  public static final String PHRASE_KEY_ADFCHANNEL_ERROR_HNDL_MSG = "ADF-MF-16103";
  public static final String PHRASE_KEY_ADFMOBILEPHONEGAPMESSAGING_ATTACHMENT_NOT_FOUND = "ADF-MF-16113";
  public static final String PHRASE_KEY_UIWEBVIEW_FN_NOT_DFN_CALL_ABORTED = "ADF-MF-16115";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_CALLING_FN = "ADF-MF-16116";
  public static final String PHRASE_KEY_SHOW_FEATURE_FAILED = "ADF-MF-16133";
  public static final String PHRASE_KEY_COULD_NOT_SHOW_FEATURE = "ADF-MF-16134";
  public static final String PHRASE_KEY_CANNOT_SEND_SMS_TITLE = "ADF-MF-16142";
  public static final String PHRASE_KEY_SMS_SERVICE_UNAVAILABLE = "ADF-MF-16143";
  public static final String PHRASE_KEY_UNABLE_TO_GET_SMS_COMPOSER = "ADF-MF-16144";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_CLASSNAME_MISSING = "ADF-MF-16145";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_FAILED = "ADF-MF-16146";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_MORPH_CLASSNAME_NIL = "ADF-MF-16147";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_METHOD_MISSING = "ADF-MF-16148";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_COULD_NOT_CREATE_CLASS = "ADF-MF-16149";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_NEW_FAILED = "ADF-MF-16150";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SELECTOR_MISSING = "ADF-MF-16151";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVOKE_ERROR = "ADF-MF-16152";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZE_ERROR = "ADF-MF-16153";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_SERIALIZED_TO_NIL = "ADF-MF-16154";
  public static final String PHRASE_KEY_CREDENTIAL_STORE_KEY_NIL_NOARGS = "ADF-MF-16156";
  public static final String PHRASE_KEY_LOGOUT = "ADF-MF-16189";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_DESCRIPTION = "ADF-MF-16203";
  public static final String PHRASE_KEY_MAIL_RESULT_FAILED = "ADF-MF-16204";
  public static final String PHRASE_KEY_MAIL_ERROR_SAVE_FAILED = "ADF-MF-16205";
  public static final String PHRASE_KEY_MAIL_ERROR_SEND_FAILED = "ADF-MF-16206";
  public static final String PHRASE_KEY_MAIL_RESULT_UNKNOWN = "ADF-MF-16207";
  public static final String PHRASE_KEY_MESSAGE_RESULT_UNKNOWN = "ADF-MF-16208";
  public static final String PHRASE_KEY_DISPLAY_FILE_FILE_NOT_FOUND_TITLE = "ADF-MF-16209";
  public static final String ACCESS_VIOLATION_MESSAGE = "ADF-MF-16213";
  public static final String ACCESS_VIOLATION = "ADF-MF-16214";
  public static final String PHRASE_KEY_UNABLE_TO_ENCRYPT_PASSWORD = "ADF-MF-16215";
  public static final String PHRASE_KEY_UNABLE_TO_GENERATE_PASSWORD = "ADF-MF-16216";
  public static final String PHRASE_KEY_UNABLE_TO_DECRYPT_PASSWORD = "ADF-MF-16217";
  public static final String PHRASE_INVALID_PARAMETER_KEY = "ADF-MF-16218";
  public static final String PHRASE_LOGIN_COMPLETE_CALL_FAILURE = "ADF-MF-16219";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_UNKNOWN_RETURNTYPE = "ADF-MF-16220";
  public static final String PHRASE_KEY_ADF_GENERIC_INVOKE_REQUEST_HANDLER_INVALID_RETURNTYPE = "ADF-MF-16221";
  public static final String PHRASE_KEY_UIWEBVIEW_PRBLM_DELIVERING_DCE = "ADF-MF-16222";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_CANCEL_MISSG_ID = "ADF-MF-16223";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_DATE = "ADF-MF-16224";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_REPEAT = "ADF-MF-16225";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_BADGE = "ADF-MF-16226";
  public static final String PHRASE_KEY_ERR_LOCAL_NOTIFY_ADD_INVALID_SOUND = "ADF-MF-16227";

}
